### ISSUE TITLE
usage with pytest unclear

### ISSUE THREAD

**Issue by brianmay** [joke2k/django-environ#102]
Not sure how to best use this with pytest. Ideally would like to be able to execute some code to setup the environment (e.g. read_env a specific file used for tests) to a known state before importing common config file, however this doesn't appear to be possible. Should be possible for a user to run "pytest" and have all tests pass without having to setup environment variables first.

**Comment by sergeyklay** [comment]
I apologize @brianmay for completely overlooking this. Thank you for the report. I know some people think this kinds of changes are trivial, but personally I believe it is important to get everything right, including CI configuration, dependency management, tests structure, and so on. Now this is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/307) branch.So thanks again for opening this issue, and for helping us make django-environ better.  And again I am sorry about the delay.
