### ISSUE TITLE
Support path-like objects

### ISSUE THREAD

**Issue by dmwyatt** [joke2k/django-environ#106]
Python 3.6 finally implements [PEP 519](https://www.python.org/dev/peps/pep-0519/).  This means we can use `pathlib.Path` instances in standard library methods that expect a string path.  For example we can do

```
a_path = Path('/home/dmwyatt/some_file.txt')
with open(a_path) as f:
    file_contents = f.read()
```

At a minimum, I recommend supporting passing path-like objects into read_env.  You can check if an object is a path-like object by using `isinstance(a_path, os.PathLike)`.  In the case of `read_env` you can probably do `isinstance(env_file, (string_types, os.PathLike))`.  You'd have to special-case for Python 3.6 vs Python <3.6.

Eventually, I think the whole `Path` class as implemented by this library can go away.

**Comment by gabn88** [comment]
Does this mean that symlinks are also allowed?

I like to symlink to an .env-example, so that on production not accidentially the .env is read (it requires a manual step of creating the symlink).

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/313) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
