### ISSUE TITLE
Why not set environment variables as string in the .env file?

### ISSUE THREAD

**Issue by gabn88** [joke2k/django-environ#110]
I see a lot of issues with urlencodig etc... So I'm just wondering why I couldn't set DATABASE_URL='the_db_url' in the .env file? That would mitigate the problems, right?

Otherwise I think I will keep using my old secret_info.txt file, which states it like this:

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'pr',
        'USER': 'pr',
        'PASSWORD': 'pa',
    }
}
```

and then gets imported like this:

`exec(open(os.path.join(os.path.dirname(BASE_DIR), 'secret_info.txt')).read())
`
And then do

```
if os.environ.get('DATABASE_URL', False):
    # If we have the DATABASE_URL set, use this. Otherwise assume it is specified in the secret_info.txt.
    DATABASES = {
        'default': env.db()  # set using django-environ and the DATABASE_URL
        }

```

**Comment by fdemmer** [comment]
> I see a lot of issues with urlencodig etc

how, where, why? can you give an example? :)

> set DATABASE_URL='the_db_url' in the .env file?

this is exactly what `django-environ` can be used for for. you can have settings in actual environment variables or a file:

- environment variable: `DATABASE_URL='postgres://foo:bar@localhost:5432/dbname'`
- or put the same in a file called `.env` and then load it like this: `environ.Env.read_env('.env'))`

**Comment by gabn88** [comment]
You are right sir. I think I misunderstood at first, but things are working fine now. Thanks!
