### ISSUE TITLE
Django 1.11 LTS Support 

### ISSUE THREAD

**Issue by stemcc** [joke2k/django-environ#116]
Mainstream support for Django 1.10 ends this month. 

Django-environ official support for 1.11 will help enable[ Django Cookiecutter to officially support 1.11 as well.  ](https://github.com/pydanny/cookiecutter-django/issues/1111 )

**Comment by edmorley** [comment]
I opened #108 in January to test against Django 1.11, however it's not yet been merged.

**Comment by joke2k** [comment]
fixed with 0.4.2
thank you
