### ISSUE TITLE
Regression in 0.4.2: fails to read values from environment

### ISSUE THREAD

**Issue by japsu** [joke2k/django-environ#118]
Value of `env.bool('DEBUG')` given `DEBUG=1` changes between 0.4.1 and 0.4.2 from `True` to `False`.

Illustrated by [this gist](https://gist.github.com/japsu/97a4307cc447652ee90dbd48714b40b5).

To reproduce:

    git clone https://gist.github.com/97a4307cc447652ee90dbd48714b40b5.git regression
    cd regression
    docker-compose up

Example output:

    Starting djangoenvironregression_environ041_1
    Starting djangoenvironregression_environ042_1
    Attaching to djangoenvironregression_environ042_1, djangoenvironregression_environ041_1
    environ042_1  | DEBUG False
    environ041_1  | DEBUG True
    djangoenvironregression_environ042_1 exited with code 0
    djangoenvironregression_environ041_1 exited with code 0

**Comment by edmorley** [comment]
Looking at the changes between 0.4.1 and 0.4.2 (https://github.com/joke2k/django-environ/compare/v0.4.1...v0.4.2) I would presume the regression is due to #105.

**Comment by japsu** [comment]
#117 similar.

**Comment by dominik-bln** [comment]
I can confirm this, our local setups are running fine with .env files, but the CI setup that uses environment variables needs a downgrade to 0.4.1

**Comment by edmorley** [comment]
@joke2k, please can you revert #105 and do another release?

**Comment by robmoorman** [comment]
Same here 0.4.2 breaks all variables.

**Comment by sergeyklay** [comment]
As far as [I see this was](https://github.com/joke2k/django-environ/pull/319) fixed. Currently all tests pass successfully. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
