### ISSUE TITLE
Add tests to catch recent regression

### ISSUE THREAD

**Issue by edmorley** [joke2k/django-environ#120]
It would be great to add some test cases that would catch the recent regression (eg #118 and friends).

**Comment by TBeijen** [comment]
Out of curiosity: Would introducing pytest be a good idea? I've become a huge fan of [pytest's parametrize](https://docs.pytest.org/en/latest/parametrize.html) and that looks very useful for quite a lot of tests here.

**Comment by sergeyklay** [comment]
As far as [I see this was](https://github.com/joke2k/django-environ/pull/319) fixed. Currently all tests pass successfully. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
