### ISSUE TITLE
'module' object has no attribute 'Env' Windows 10

### ISSUE THREAD

**Issue by nguyentrantuan** [joke2k/django-environ#125]
Installed Python 2.7 on Windows 10. Found nowhere to resolve this errors. Any help?

>>> import environ
>>> env=environ.Env()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Env'

**Comment by garrykevin-ep** [comment]
pip install django-environ

**Comment by joke2k** [comment]
Yep... just install the package plz
