### ISSUE TITLE
PgBouncer and django.db.utils.OperationalError: FATAL 

### ISSUE THREAD

**Issue by murdav** [joke2k/django-environ#127]
Hello,

Currently it seems it's not possible to use PgBouncer:
DATABASE_URL=postgis://myuserdb:mydbpasswd@/var/run/postgresql:6432/mydb

I got
django.db.utils.OperationalError: FATAL:  database "var/run/postgresql:6432/mydb" does not exist

Thanks,

D

**Comment by hammadzz** [comment]
@murdav you sure it was caused by django-environ? I suspect it must have been pgbouncer configuration as it should just work like a regular Postgres connection.

**Comment by hammadzz** [comment]
https://github.com/joke2k/django-environ/pull/158

Could this be the actual issue?

**Comment by murdav** [comment]
Yes, that it's the case! ? I'm going to close this in favour of #158.
