### ISSUE TITLE
Postgres schema to .env file

### ISSUE THREAD

**Issue by diegogslomp** [joke2k/django-environ#137]
Hello!

At my original settings.py I have this configuration to set the postgres database schema. How can I set this in a django-environ .env file?
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'OPTIONS': {
            'options': '-c search_path=public'
        },
```

**Comment by diegogslomp** [comment]
Changed manually using 'SET search_path TO myschema,public;' from psql cli

**Comment by clintonb** [comment]
dj-database-url supports this: https://github.com/kennethreitz/dj-database-url/pull/59. It would be great if this functionality was incorporated into this package.

**Comment by clintonb** [comment]
For future readers, you can set the options query string to define the search path:

`DATABASE_URL=psql://user:pass@db.example.com:5432/test_db?options=-c%20search_path%3Dmyschema`

This will result in the following Django `dict` being rendered:

```python
{
    'ENGINE': 'django.db.backends.postgresql',
    'NAME': 'test_db',
    'USER': 'user',
    'PASSWORD': 'pass',
    'HOST': 'db.example.com',
    'PORT': '5432',
    'OPTIONS': {
        'options': '-c search_path=myschema'
    }
}
```
