### ISSUE TITLE
Exclude tests from package on PyPI

### ISSUE THREAD

**Issue by edmorley** [joke2k/django-environ#141]
Currently the package on PyPI includes the tests:
```
environ/test.py
environ/test_env.txt
environ/tests/__init__.py
environ/tests/functional_tests.py
environ/tests/test_environment.py
```

This accounts for over half the package size.

**Comment by joke2k** [comment]
Next release will fix it 
https://github.com/joke2k/django-environ/commit/dcd8353946a80b1c5da619f56d05587325ea7a6b
Thank you for waiting... .... :D
