### ISSUE TITLE
For Multiple Environments

### ISSUE THREAD

**Issue by callsamleung** [joke2k/django-environ#143]
Hi all,
django can use '--settings [settings.py]' to let the same code run under the difference settings.

can we have some way to do that? 

Like this.
```
python manager.py runserver --env_file path/of/.env1
python manager.py runserver --env_file path/of/.env2
```

**Comment by joke2k** [comment]
Hi @callsamleung 

your request is very common but it doesn't concern only django-environ because in your example involve the arg parsing of runserver.
Of course you can use some like that:
```bash
ENV_PATH=.env1 python manage.py runserver
```
and read the os environment variable in settings.py:
```python
import environ
env = environ.Env()
ENV_PATH = env.str('ENV_PATH') # care about default here..
# and then read the correct .env file:
env.read_env('path/of/' + ENV_PATH)
```

**Comment by shawnngtq** [comment]
@joke2k 

If I have multiple environments, the proper way to manage them is to create multiple `env` files?

For example
```
# production
ENV_PATH=.env_prod python manage.py runserver

# local
ENV_PATH=.env python manage.py runserver
```

**Comment by joke2k** [comment]
yes definitely!
One .env file for each environment (es: local, staging, production)
