### ISSUE TITLE
[duplicated] about spaces around equal sign

### ISSUE THREAD

**Issue by vanyakosmos** [joke2k/django-environ#144]
[Original issue.](https://github.com/joke2k/django-environ/issues/35)

With spaces around '=' config looks much more friendly and readable. I still don't understand why it is necessary to comply with this 'convention' and break readability...
Spaces around '=' don't break anything, there is no value that needs spaces at the beginning, and if there is then value can be surrounded by quotes.

Also when my .env file was 'malformed' with spaces and I tried to read some var I got `KeyError` instead of `ParsingError` (or something like this). It was real pain in the neck to find out what was actually wrong...

**Comment by memclutter** [comment]
@vaniakosmos this feature refers to the package [envarse](https://github.com/rconradharris/envparse), because It is there that parsing `.env` files. 

Also, it's more about declaring variables in [linux OS](https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-a-linux-vps).

**Comment by nodje** [comment]
I totally agree with @vanyakosmos, this no-space in `.env` file convention makes no sense. Space around = sign should be supported, like in many other languages.

And that part come from `django-environ` (and originally from `honcho` apparently): https://github.com/joke2k/django-environ/blob/develop/environ/environ.py#L645
```
m1 = re.match(r'\A(?:export )?([A-Za-z_0-9]+)=(.*)\Z', line)
```
should simply be 
```
m1 = re.match(r'\A(?:export )?([A-Za-z_0-9]+\s?)=(\s?.*)\Z', line)
or
m1 = re.match(r'\A(?:export )?([A-Za-z_0-9]+ ?)=( ?.*)\Z', line)
or to be more clear maybe
m1 = re.match(r'\A(?:export )?([A-Za-z_0-9]+[ ]?)=([ ]?.*)\Z', line)
```

**Comment by vanyakosmos** [comment]
Or like this:
```python
m1 = re.match(r'\A(?:export )?([A-Za-z_0-9]+)(=| = )(.*)\Z', line)
```
to ensure that spaces around `=` are placed on both sides at the same time intentionally.

**but**

I think @memclutter is right though. If something was built around specific tool then this something should comply with the way how this specific tool works and avoid any customization which can confuse developers. In our case this something is `django-environ` and 'tool' is shell and the way how env vars are created. If shell allow only one way to create env vars then .env readers should also read only in one way. Most people already get used to the absence of spaces around `=` and will be surprised that ` = ` with spaces works too (or they might expect completely different behavior).
