### ISSUE TITLE
Problem Sending Mail using ENV

### ISSUE THREAD

**Issue by dinesh829269** [joke2k/django-environ#146]
I am using Django Edge Project that has django-environ installed, 
I need to send Email using TLS, 
my email string is :
EMAIL_URL=smtp+tls://myusername@gmail.com:mypassword@smtp.gmail.com:587
and in settings
EMAIL_CONFIG = env.email_url(
            'EMAIL_URL', default='smtp+tls://username@gmaillcom@:password@smtp.gmail.com:587')
vars().update(EMAIL_CONFIG)

But when i am sending Email, 
It sends from webmaster@localhost, its not picking smtp configurations.

**Comment by memclutter** [comment]
What is the value in [DEFAULT_FROME_EMAIL](https://docs.djangoproject.com/en/1.11/ref/settings/#default-from-email)?

**Comment by richardbalwane** [comment]
@memclutter that was the answer.
Someone please close this one.
