### ISSUE TITLE
0.3.1 missing from PyPI

### ISSUE THREAD

**Issue by rouge8** [joke2k/django-environ#16]
[PyPI only has 0.3.0](https://pypi.python.org/pypi/django-environ). Could you push up 0.3.1?

Also, if it's not too much trouble, could you add git tags for the releases?

**Comment by edmorley** [comment]
@joke2k I don't suppose you could add 0.3.1 to PyPI?
Thanks :-)

**Comment by joke2k** [comment]
@edmorley today is a release day for 0.3.1 keep in touch

**Comment by joke2k** [comment]
Hi @edmorley today i will release a 0.4.0 and 0.3.1 versions on pypi.
Forgive me for being late.

**Comment by edmorley** [comment]
That's great - thank you :-)

**Comment by joke2k** [comment]
Uploaded both on pypi.
