### ISSUE TITLE
Floats can only be positive values

### ISSUE THREAD

**Issue by mheppner** [joke2k/django-environ#160]
Due to the [regex used](https://github.com/joke2k/django-environ/blob/628ed38e540ec9a6f3aff622953948e54f14a76d/environ/environ.py#L332) when casting floats, negative values are converted to positive, since hyphens are removed. There doesn't seem to be any test cases that cover this either.

**Comment by Alig1493** [comment]
I think adding ?- will probably solve the issue

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/318) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
