### ISSUE TITLE
Remove Django dependency or make it optional

### ISSUE THREAD

**Issue by K377U** [joke2k/django-environ#161]
I would like to use this package for non-django project but the dependency requirement is a bit heavy for small command line applications.

Django is set in install_requires but it is not used in the package. Only tests are using it. Would it be possible to remove this dependency from install_requires?

**Comment by chris-erickson** [comment]
@joke2k What do you think about this?  It seems that when the only dependency I can find doesn't exist, it [has a sane fallback](https://github.com/joke2k/django-environ/blob/develop/environ/environ.py#L12-L19).

This is one of the best env tools, and I use it outside many Django apps.

**Comment by joke2k** [comment]
Hi @K377U and @chris-erickson see #73
