### ISSUE TITLE
Docs / Feature for nested lists

### ISSUE THREAD

**Issue by epicserve** [joke2k/django-environ#166]
Maybe I'm just missing it but what is a way to change the ADMINS setting so it uses an environment variable?

**Comment by Jafnee** [comment]
I don't think there's a way to pass in nested list/tuple straight from env, but something like this would work.

ENV
```bash
DJANGO_ADMINS=jafnee:my@email.com,brent:another@email.com
```

settings.py
```python
ADMINS = [x.split(':') for x in env.list('DJANGO_ADMINS')]

**Comment by epicserve** [comment]
This looks like a decent solution. Is this worth putting in the readme?

**Comment by Jafnee** [comment]
I think it'd fit in with the other tips https://github.com/joke2k/django-environ#tips

**Comment by theskumar** [comment]
@epicserve @Jafnee have a look at https://github.com/joke2k/django-environ/pull/167#pullrequestreview-89042631

**Comment by epicserve** [comment]
@theskumar, I commented on your PR.

**Comment by joke2k** [comment]
Added to Tips.

Thank you
