### ISSUE TITLE
environ should be able to infer casting type from the default

### ISSUE THREAD

**Issue by crccheck** [joke2k/django-environ#17]
If you have `DEBUG = env('DEBUG', default=False)`, having to also specify `env = environ.Env(DEBUG=(bool, False),)` seems redundant. For example, see http://tornado.readthedocs.org/en/latest/options.html#tornado.options.OptionParser.define

> If type is given (one of str, float, int, datetime, or timedelta) or can be inferred from the default, we parse the command line arguments based on the given type.

**Comment by joke2k** [comment]
These options are alternatives, you can use the template mode initializing the Env with defaults and casting, or use the single one.
