### ISSUE TITLE
Proposition to change env file format to allow it to be Ansible compatible

### ISSUE THREAD

**Issue by ArtemBernatskyy** [joke2k/django-environ#172]
Hello guys, great package.

I think we need to make env file compatible with `Ansible` yml env file.  
Thus allows us to have single env file for both `django-environ` and `Ansible`.  

Any thoughts about this ?

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
