### ISSUE TITLE
Order of importance of engine configuration in db_url_config

### ISSUE THREAD

**Issue by ddiazpinto** [joke2k/django-environ#175]
According to this code in ```db_url_config```:
``` python
class Env(object):
    # [...]
   @classmethod
    def db_url_config(cls, url, engine=None):
        # [...]
        if engine:
            config['ENGINE'] = engine
        if url.scheme in Env.DB_SCHEMES:
            config['ENGINE'] = Env.DB_SCHEMES[url.scheme]


        if not config.get('ENGINE', False):
            warnings.warn("Engine not recognized from url: {0}".format(config))
            return {}
```

If you configure a backend using the ```engine``` parameter of ```Env.db()```:

``` python
import environ
env = environ.Env()
env.db('DATABASE_URL', engine='path.to.engine')
```
The engine is going to be overriden by the scheme you have put in ```DATABASE_URL``` (if it is exists in ```Env.DB_SCHEMES```. see #173).

I think that it is a misbehaviour. The ```engine``` parameter of ```Env.db()``` should be the last to be checked, because this function is acting as a wrapper of ```DATABASE_URL```. What do you think?

**Comment by Darkless012** [comment]
Please merge this, I've just spend more than comfortable time of debugging set engine.

**Comment by joke2k** [comment]
Thank you guys, sorry for lazy merge
