### ISSUE TITLE
Support sqlite database urls relative to project path. 

### ISSUE THREAD

**Issue by thomasf** [joke2k/django-environ#187]
When developing it makes sense to have the database file in the local repository directory, to have a `dev.env` which is valid for all developers it needs to be relative..

I have been doing hacks in settings.py to get around it for a few years now but I would like a discussion about how to maybe integrate such a feature into django-environ.

This basically just assumes that if the the file is at the root of the system it's instead relative but I'm looking for a way to get rid of these in every project..
```py
for db in DATABASES:
    if DATABASES[db]['ENGINE'] == 'django.db.backends.sqlite3':
        if os.path.split(DATABASES[db]['NAME'])[0] == "/":
            DATABASES[db]['NAME'] = root(DATABASES[db]['NAME'][1:])
```

I am thinking that this is kind of sane because no one proably stores the database in the root of the file system but making it optional by having a `sqlite_root` argument to the db-url function maybe works? 

```py
root = environ.Path(__file__) - 2
...
DATABASES = {
    'default': env.db(sqlite_root=root()),
}
```

I think that both relative AND absolute paths should work.

One option which I think might work safely for triggering a relative path instead of absolute is to do it when host is `.` or some other reserved name which isn't really a hostname. It should error out if `sqlite_root` was not provided to the url parse function.
```py
DATABASE_URL=sqlite://./db.sqlite3
 ```

Please share your opinions on this..

**Comment by joke2k** [comment]
Hi @tomasf 
The file url syntax for dbs allows you to put you db everywhere in your filesystem.
Relative or absolute too.
See the tips for sqlite in Readme.
If I correctly understand what do you mean, you need to have `dev.env` with relative path for db... so you can use
sqlite:///db.sqlite for a db in the same dir of .env file and
sqlite://../db.sqlite for relative one and
sqlite:////home/user/db.sqlite for absolute one.
Is it right for you?

**Comment by thomasf** [comment]
Ok, it just became more tricky latley it seems..
The problem with `sqlite:///db.sqlite` is that it is relative to PWD instead of the project root.

This one maybe has stopped working recently(?)
```
DATABASE_URL=sqlite://../db.sqlite3

...settings.py:171: UserWarning: SQLite URL contains host component '..', it will be ignored
  'default': env.db(),
{'default': {'NAME': 'db.sqlite3', 'USER': '', 'PASSWORD': '', 'HOST': '..', 'PORT': '', 'ENGINE': 'django.db.backends.sqlite3'}}

```

**Comment by thomasf** [comment]
Maybe you were not saying that it already should work?.. But yes, I mostly want that absolute and relative to some root defined in `settings.py` to both work.

**Comment by joke2k** [comment]
Sure, I wrote badly `//../` doesnt' work. sorry

But `sqlite:///../sqlite.db` works with relative to your pwd... and pwd is the directory that you set in your nginx, uwsgi.. apache config, or, in development, the path of manage.py.
Actually is django that resolves sqlite:/// to pwd.

Your suggestion to use the `dot` to trigger relative path to a `sqlite_root` parameter seems to be a repetition. You could use Path to handle that.

**Comment by thomasf** [comment]
> Actually is django that resolves sqlite:/// to pwd.
This is what I need to override,, When using a shell I execute manage.py from the directory I'm in, not necessarily the root of the project.. 

 `python ../manage.py runserver` doesnt work and it's only because the database url  since `root = environ.Path(__file__) - 2` takes care of making everything else to be relative to the project root instead 
 of PWD.. It's strange that the database url is the only exception without adding code to each projects `settings.py` to handle it.

**Comment by thomasf** [comment]
I am suggesting `.` as the hostname since that currently has no semantic meaning with sqlite.. Any other keyword would also work for me.. I don't know which word or symbol would communicate that the magic hostname refers to an additional argument to `env.db` and related functions.. 

This is maybe similarly confusing but more verbose which maybe makes it clearer.

```py
DATABASES = {
    'default': env.db(sqlite_root=root()),
}

DATABASE_URL=sqlite://root//db.sqlite3
```

**Comment by sergeyklay** [comment]
I'd like django-environ remain simple as long as possible. I'd not complicate its codebase without an urgent and obvious need. To all those who want to work with relative paths, I would recommend some kind of approach like this:

```shell
# .env file contents
DATABASE_URL=sqlite:///db.sqlite3
```

```py
# settings.py file contents
import environ
import os


env = environ.Env()

# Set the project base directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
env.read_env(os.path.join(BASE_DIR, '.env'))


def get_db_config(environ_var):
    """Get Database configuration."""
    options = env.db(var=environ_var, default='sqlite:///db.sqlite3')
    if options.get('ENGINE') != 'django.db.backends.sqlite3':
        return options

    # This will allow use a relative to the project root DB path
    # for SQLite like 'sqlite:///db.sqlite3'
    if not options['NAME'] == ':memory:' and not os.path.isabs(options['NAME']):
        options.update({'NAME': os.path.join(BASE_DIR, options['NAME'])})

    return options


DATABASES = {
    'default': get_db_config('DATABASE_URL'),
}
```
