### ISSUE TITLE
[RFC] Add support for docker-style _FILE environment variables

### ISSUE THREAD

**Issue by apollo13** [joke2k/django-environ#189]
I'd like to add support for docker-style `_FILE` environment variables. What this would mean basically is the following:

Take this line as an example:
```
DATABASES = {'default': env.db(default=sqlite_default)}
```
This will make `environ` look for a `DATABASE_URL` and use that. I'd like to extend it to first look for `DATABASE_URL_FILE` and if that variable exists and is set read the file it points to and use that instead of `DATABASE_URL`.

The idea here is that stuff like docker swarm secrets are injected as files into your container and I'd need an easy way to reference those. You can find more information about it at https://hub.docker.com/r/_/postgres/ (scroll down to `Docker Secrets`). Note that while I am referring solely to docker here, the same holds true for any other system which injects secrets as files and not environment variables.

Backwards compatibility wise there should be no issue;
```
env('ASD_FILE')
```
would try `ASD_FILE_FILE` and not read `ASD_FILE` as file directly...

If you think this is a good idea I'll happily supply a PR; if you are need more convincing please also tell me :)

**Comment by valberg** [comment]
@apollo13 have you done any work on this?

**Comment by apollo13** [comment]
Nope

**Comment by sergeyklay** [comment]
This is resolved in [`main`](https://github.com/joke2k/django-environ/pull/328) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
