### ISSUE TITLE
read_env path

### ISSUE THREAD

**Issue by synotna** [joke2k/django-environ#19]
When running read_env without providing a filename, it looks for .env in the current directory (i.e. /project/project/.env), when providing a filename it looks in the parent directory (i.e. /project/.env/)

Shouldn't the behaviour be the same in both cases?

**Comment by julianwachholz** [comment]
I think this is undefined behaviour. But you should use absolute paths anyway, don't you agree? ;)

**Comment by synotna** [comment]
After re-reading the docs with a fresh mind, I see the behaviour is defined "If not given a path to a dotenv path, does filthy magic stack backtracking to find manage.py and then find the dotenv."

The change in behaviour from "load .env from the current directory" to "relative to manage.py" did not feel natural :)

Considered closed!
