### ISSUE TITLE
'+'es are stripped from passwords

### ISSUE THREAD

**Issue by ajhodges** [joke2k/django-environ#194]
I'm using django-environ to read passwords that are generated by AWS (i.e. the SES SMTP credentials, which use an AWS Secret as the password). These passwords can have '+' symbols in them, which are stripped by `_cast_urlstr()`/`unquote_plus()`.

I think for now my temporary fix is to urlencode the passwords, but I feel like I shouldn't have to do that.

**Comment by ntravis** [comment]
It's documented in the README and has been that way since 2016. The maintainer is generally open to PRs if you can account for unsafe characters and provide test cases.

https://github.com/joke2k/django-environ#using-unsafe-characters-in-urls

**Comment by pssuils** [comment]
We just run into the same problem 😬. For the moment we'll need to change our passwords to not contain any `+` however I 👍 that the *passwords* could include `+`.

**Comment by sergeyklay** [comment]
@ajhodges Please take a look at this answer https://github.com/joke2k/django-environ/issues/288#issuecomment-908320933
