### ISSUE TITLE
Include TEST db in DATEBASE_URL

### ISSUE THREAD

**Issue by aldokkani** [joke2k/django-environ#196]
Django Database settings allows you to spicify the database for testing like the following

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'USER': 'mydatabaseuser',
        'NAME': 'mydatabase',
        'TEST': {
            'NAME': 'mytestdatabase',
        },
    },
}
```
So how can I do this from DATEBASE_URL?

**Comment by MateuszGrabuszynski** [comment]
As far as I know, you can do it like that:
1) `DATABASES = {'default': env.db()}`  
which should read from env 'DATABASE_URL';
2) `DATABASES['default']['TEST'] = {'NAME': 'mytestdatabase'}`
just after the 1). But I am not 100% sure if that works, sorry.

**Comment by sergeyklay** [comment]
Yet another solution is to use `DATABASES['default'].update({'TEST': {'NAME': 'mytestdatabase'}})`

**Comment by sergeyklay** [comment]
I'm closing since this is a not a bug report. Please check the mentioned solutions. If you are still experiencing this and have some more additional info feel free open a new issue.
