### ISSUE TITLE
Using '$' inside .env File being evaluated incorrectly because of PROXY

### ISSUE THREAD

**Issue by kshitijgorde** [joke2k/django-environ#207]
Here is my .env file
EMAIL_HOST_USER='xyz@gmail.com'
EMAIL_HOST_PASSWORD='$xyz'

*** This leads to the following error **
ImproperlyConfigured
It thinks that xyz is another variable.

**Comment by sergeyklay** [comment]
I am closing this issue as a duplicate https://github.com/joke2k/django-environ/issues/271
