### ISSUE TITLE
Got problem with env.email_url('EMAIL_URL') in .env file

### ISSUE THREAD

**Issue by ghost** [joke2k/django-environ#212]
I'm using EMAIL_URL in Django settings.py，here is my setting:
```
EMAIL_CONFIG = env.email_url('EMAIL_URL')
vars().update(EMAIL_CONFIG)
```
this is my `.env` file
`EMAIL_URL=smtp+ssl://fake@fake.com@:mypassword@smtp.qiye.aliyun.com:465`
I am sure that all my infomation is correct, but I always got this error
```
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (526, b'Authentication failure[0]')
[01/Feb/2019 17:43:38] "POST /accounts/email/ HTTP/1.1" 500 149193
```
Is there anything wrong with **EMAIL_URL** setting in `.env` file?

**Comment by sergeyklay** [comment]
Please take a look at this answer https://github.com/joke2k/django-environ/issues/288#issuecomment-908320933
