### ISSUE TITLE
problems with lists in .env

### ISSUE THREAD

**Issue by ezzra** [joke2k/django-environ#214]
I don't know if I am using this wrong here, but if, it does not look straight forwarded to me. I have this in settings.py

```
env = environ.Env(
    ALLOWED_HOSTS=(list, ['127.0.0.1', 'localhost']),
)
```
and this in `.env`

`ALLOWED_HOSTS=['127.0.0.1', 'localhost']`

Which wont work, because `env('ALLOWED_HOSTS')` will return `["['127.0.0.1', 'localhost']"]`. But it should be `['127.0.0.1', 'localhost']` of course. If I try to use it without the `list` parameter in `.Env`, I will get an not callable error.

How can I manage, to use a list in `.env` as well?

**Comment by ptink** [comment]
the syntax for lists in the `.env` file is comma separated values so it would be `ALLOWED_HOSTS=127.0.0.1,localhost`

**Comment by ezzra** [comment]
ah ok, good to know, is that documented somewhere?

**Comment by ptink** [comment]
https://django-environ.readthedocs.io/en/latest/#supported-types

Next to some of the types there's an example usage

**Comment by tacan** [comment]
Hey guys, I am using django-environ with Django3.2 now and the list or tuple syntax you suggest isn't working. I am using a somewhat ugly workaround like so.

The line in my .env file is;
ALLOWED_HOSTS=["localhost", "127.0.0.1", "serviskayit.viessmann.com.tr"]

The line in my settings.py is;
ALLOWED_HOSTS = json.loads(env('ALLOWED_HOSTS'))

Hope it helps as a band-aid but I also hope to see a fix.

**Comment by sergeyklay** [comment]
```shell
# Comma-separated list
ALLOWED_HOSTS=.localhost,127.0.0.1,[::1]

# Comma-separated list
INTERNAL_IPS=.localhost,127.0.0.1,[::1]
```

```py
from pathlib import Path
from environ import environ


env = environ.Env(
    ALLOWED_HOSTS=(list, []),
    INTERNAL_IPS =(list, []),
)


BASE_DIR = Path(__file__).resolve().parent.parent
env.read_env(BASE_DIR / '.env')


ALLOWED_HOSTS = env('ALLOWED_HOSTS')
INTERNAL_IPS = env('INTERNAL_IPS')
```

**Comment by sergeyklay** [comment]
Also see: https://github.com/joke2k/django-environ/issues/231#issuecomment-555308761

**Comment by sergeyklay** [comment]
I'm closed since this is a not a bug report. Please check the mentioned solutions. If you are still experiencing this and have some more additional info feel free open a new issue.
