### ISSUE TITLE
Basic example not working

### ISSUE THREAD

**Issue by alvarolloret** [joke2k/django-environ#217]
I'm trying to setup the .env  for a Django project. However, it seems that not even the basic example works. Just trying to setup the variable `DEBUG` in the .env file. I must be missing something:

Steps to reproduce the behaviour --> From `python manage.py shell`:
```
import environ
env = environ.Env(
    DEBUG=(bool, True),
)
print(env('DEBUG'))
open('.env', 'a').write('DEBUG=False')
environ.Env.read_env('.env')
print(env('DEBUG'))
```
no matter what I write, the env outputs all the Time false. What am I missing

**Comment by joke2k** [comment]
Hi @alvarolloret 

It seems that something in your python environ is not well configured.
Can you share how you setup django? Using virtualenv? Pipenv? or something else?
Post the result of these commands please: 
`echo $PYTHONPATH`
`pip freeze`

**Comment by romgar** [comment]
I just went through some troubles with `pipenv`, which automatically loads as environment variable any values defined in a `.venv` file it can find at the root of the project (https://docs.pipenv.org/en/latest/advanced/#automatic-loading-of-env).
If you are in this situation, that could explain the first `print`, getting the value from the environment setup by `pipenv`.
