### ISSUE TITLE
DEBUG=on and off

### ISSUE THREAD

**Issue by sant527** [joke2k/django-environ#218]
in .env we have
DEBUG=on

so if i dont want DEBUG then what should i do in .env
DEBUG=off  or
DEBUG=False

Why we are using DEBUG=on instead of DEBUG = True

**Comment by Jafnee** [comment]
As long as the value is any of the ones listed [here](https://github.com/joke2k/django-environ/blob/develop/environ/environ.py#L60) it will be treated as `True`. Any values that don't fall under there will be treated as `False`.

`BOOLEAN_TRUE_STRINGS = ('true', 'on', 'ok', 'y', 'yes', '1')`

**Comment by sant527** [comment]
thanks

**Comment by joke2k** [comment]
Thanks to @Jafnee :D
