### ISSUE TITLE
Using Variables in .env File

### ISSUE THREAD

**Issue by waspinator** [joke2k/django-environ#219]
how would I use variables inside the .env file?

for example, how would I define the `DATABASE_URL`  using other variables?

```
DB_HOST=myhost
DB_PORT=3306
DB_NAME=mydb
DB_USER=myuser
DB_PASSWORD=mypassword
DB_CHARSET=utf8mb4

DATABASE_URL=mysql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?charset=${DB_CHARSET}
```

**Comment by Thijss** [comment]
I don't believe this is possible. However, you can just as easily define DATABASE_URL in your python code.
```python
DATABASE_URL="mysql://{}:{}@{}:{}/{}?charset=${}".format(
    env("DB_USER"),
    env("DB_PASSWORD"),
    env("DB_HOST"),
    env("DB_PORT"),
    env("DB_NAME"),
    env("DB_CHARSET"))
```

**Comment by CaveSven** [comment]
@waspinator this approach is working for me.

**Comment by kyungjunleeme** [comment]
In my case, 

In settings.py

DATABASES = {
    # The db() method is an alias for db_url().
    'default': env.db(),
}

In .env
DATABASE_URL=postgres://user:password@host/name (your have to replace example data your data
