### ISSUE TITLE
How do you write to .env variables?

### ISSUE THREAD

**Issue by pjonson2** [joke2k/django-environ#229]

**Comment by joke2k** [comment]
Hi @pjonson2 
what do you mean with .env variables?

Try to see if Proxy can help you:
https://github.com/joke2k/django-environ#proxy-value

And check this issue #219 for further information on how to use it.

Thank you

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
