### ISSUE TITLE
how to pass allowed_hosts default value

### ISSUE THREAD

**Issue by sant527** [joke2k/django-environ#231]
I have the following in my settings.py file

```
import environ
env = environ.Env( ALLOWED_HOSTS=(list, ['127.0.0.1:8000']))
ALLOWED_HOSTS = env('ALLOWED_HOSTS')
```
my .env file is empty presently

The above i am doing for testing

when i try to access 127.0.0.1:8000 it says
`Invalid HTTP_HOST header: '127.0.0.1:8000'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.`

Inspite of passing the ALLOWED_HOSTS default value without having the variable in .env file  [127.0.0.1] is not assigned.

So is it necessary that i should have the ALLOWED_HOSTS mentioned in the env file like and when its left blank then only 
`env = environ.Env( ALLOWED_HOSTS=(list, ['127.0.0.1:8000'])) will work`
.
env file
`ALLOWED_HOSTS=`

**Comment by mcauto** [comment]
env file

`ALLOWED_HOSTS=example.com,localhost`

```python
env = environ.Env(
    ALLOWED_HOSTS=(list, [])
)
ALLOWED_HOSTS: List[str] = env('ALLOWED_HOSTS')

print(ALLOWED_HOSTS)
```

and run

```bash
$ python manage.py runserver
['exmaple.com', 'localhost']
```

**Comment by fpuga** [comment]
Just in case someone is looking for a different solutions this is what I'm doing (based on the test: `test_empty_list`):

env file:
```text
ALLOWED_HOSTS=
```

seetings.py:
```python

ALLOWED_HOSTS = env("ALLOWED_HOSTS", cast=[str])
```

This set an empty list '[]'  as the value of `ALLOWED_HOST` in `seetings.py` that is  the default value.
