### ISSUE TITLE
Support Django 3.0

### ISSUE THREAD

**Issue by auvipy** [joke2k/django-environ#239]

**Comment by makmary170** [comment]
+1

**Comment by wahello** [comment]
+1

**Comment by jcquarto** [comment]
+1+1 .   Kinda makes django-environ pointless if Django 3 isn't supported

**Comment by MarkKoz** [comment]
What exactly isn't working in Django 3.0? For my needs, everything is ostensibly working fine so far.

**Comment by jcquarto** [comment]
slightly different than the documentation, I got it to work by doing this (Django 3):

import environ

```
root = environ.Path(__file__) - 2  # get root of the project
env = environ.Env()
#environ.Env.read_env(os.path.join(root(), '.env'))  # reading .env file
environ.Env.read_env(root() + '/.env')  # reading .env file
```

**Comment by ekersten** [comment]
If it helps anyone, I've solved it like this on a Django 3.1.2 project


`<project_dir>/settings/base.py`
```
import os
import environ

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

```

Would be nice to have this included in the docs

**Comment by j0hnnyx** [comment]
I'm using Django 3.1.5 and below works for me:
```
BASE_DIR = Path(__file__).resolve().parent.parent.parent
env = environ.Env()
ENV_FILE = ".env/.prod/.django"
env.read_env(os.path.join(BASE_DIR, ENV_FILE))
```
But how would I override these settings on django dev server start? 
below doesn't work:
`ENV_FILE=.env/.local/.django ./manage.py runserver`

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/307) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
