### ISSUE TITLE
make a new PyPi release so that docs match behaviour

### ISSUE THREAD

**Issue by brki** [joke2k/django-environ#24]
On readthedocs, we see this example for the .env file:

```
DATABASE_URL=psql://urser:un-githubbedpassword@127.0.0.1:8458/database
```

But this doesn't work with the latest version available on PyPi.   Looks like 'psql' was introduced later ... pgsql, postgres, postgresql work, but not psql.

**Comment by joke2k** [comment]
I'll fix this with new release soon
