### ISSUE TITLE
Make .env file optional in read_env method

### ISSUE THREAD

**Issue by afilardo** [joke2k/django-environ#243]
Hi,

I think that this proposal is interesting because I can imagine that more devs have been in the same situation multiple times:

- I want to use _.env_ file when working locally.
- But it is a bad practice to push _.env_ file to GitHub.
- I have a SECRET_KEY that it is required. If it is no present, Django app will raise `ImproperlyConfigured`, which is fine.
- I don't want to set this env vars in my computer each time (that is why we use .env file).
- But I know that it is mandatory in PROD env, which is fine too.

Having an optional ._env_ file will allow us to have the `read_env` method in our base_settings file, which will work in PROD env too (where we don't have _.env_ file).

The `read_env` method should read the file (if present) and add their vars to the environment scope.
If the file is not present and I forgot to set any var, Django app will raise the `ImproperlyConfigured` exception.
I think there is no risk in making this file optional.
At this moment, Django app does not run if the _.env_ file is not present.

This is just my opinion. I would like to know how you handle this situation, and what do you think about my proposal.

Regards

**Comment by herrboyer** [comment]
As a workaround you could

```python
PROJECT_ROOT = environ.Path(__file__) - 3
try:
    PROJECT_ROOT.file(".env")
    environ.Env.read_env(PROJECT_ROOT(".env"))
except FileNotFoundError:
    pass
```

**Comment by afilardo** [comment]
Yeah, it is what I'm using, but I find it unnecessary

**Comment by eedwards-sk** [comment]
I agree with OP, since `django-environ` should not get in the way of 12factor configuration. Requiring an `.env` file breaks that contract.

**Comment by amazingandyyy** [comment]
this is project is so bad if dev cannot sepefic file name instead of .env, since django runner will always create `.env` folder............. any ideas?????

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/251) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
