### ISSUE TITLE
Won't update environ key if it already set

### ISSUE THREAD

**Issue by yzdann** [joke2k/django-environ#249]
imagine a case when we need to update some of the production settings in `production.py` base on `base.py`.

```py
from .base import *

environ.Env.read_env(env_file="/etc/<app>/.env")

DATABASES = {
    # read os.environ['DATABASE_URL'] and raises ImproperlyConfigured exception if not found
    "default": env.db(),
}

CELERY_BROKER_URL = env("REDIS_URL")
CELERY_RESULT_BACKEND = env("REDIS_URL")
CACHEOPS_REDIS = env("CACHE_URL")

...
``` 

since code used `setdefault` it will ignore to update that in `django-environ/environ/environ.py`
```py
# line 654
cls.ENVIRON.setdefault(key, str(val))
```

**Comment by sdementen** [comment]
any update on a fix for this issue ?

**Comment by sdementen** [comment]
for info, a quick fix can be to add
`env.ENVIRON.setdefault = env.ENVIRON.__setitem__`
just after declaring the env variable (with `environ.Env()`)

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/329) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
