### ISSUE TITLE
Support section

### ISSUE THREAD

**Issue by alexsilva** [joke2k/django-environ#25]
It would be great if the file '.env' had support sections. So I would not have to keep repeating the same prefix (ZENDESK), as in:

```
ZENDESK_URL_COMPANY_NAME=xxx
ZENDESK_EMAIL=xxx
ZENDESK_PASSWORD=xx
ZENDESK_API_VERSION=2
```

Sections

```
[ZENDESK]
  URL_COMPANY_NAME=xxx
  EMAIL=xxx
  PASSWORD=xx
  API_VERSION=2
```

I did not see anything about it in the documentation, is there any solution to this ?

**Comment by pydanny** [comment]
How would this work in Django settings? Your wish simply doesn't work for Python.

**Comment by pombredanne** [comment]
@alexsilva my 2 cents: it would make the reading of the .env file harder and less explicit.
There are times when repetition is not a problem IMHO.

**Comment by joke2k** [comment]
I agree with @pydanny and @pombredanne 
Thank you for question anyway
