### ISSUE TITLE
Code block is missing on RTFD for Multiple env files

### ISSUE THREAD

**Issue by chitak** [joke2k/django-environ#254]
The code block is missing for documentation on RTFD.

Please refer to the screenshot below:

**Github README**:
<img width="903" alt="github" src="https://user-images.githubusercontent.com/665982/77299664-c7b68080-6d27-11ea-976e-395148164f59.png">
https://github.com/joke2k/django-environ/tree/dc2d281e45eb41a723549e01e435ae1fe89b0a96#multiple-env-files

**RTFD**:
<img width="706" alt="readthedocs" src="https://user-images.githubusercontent.com/665982/77299687-ce44f800-6d27-11ea-8efe-594eb28a6407.png">
https://django-environ.readthedocs.io/en/latest/#multiple-env-files

**Comment by rennard** [comment]
+1, just spent quite a while looking for this. Thanks!

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/308) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
