### ISSUE TITLE
RTD docs on ENV_PATH are misleading / mis-aligned with 0.4.5 release 

### ISSUE THREAD

**Issue by dwightgunning** [joke2k/django-environ#258]
_(I expect this will be resolved in the next release but decided to raise it in case others are tripped up on it like I was. I couldn't find any other issue describing the situation.)_

The section [Multiple env files](https://django-environ.readthedocs.io/en/latest/#multiple-env-files) published to Read The Docs indicates that setting the `ENV_PATH` environment variable will instruct django-environ to use the alternative file.

However, in addition to setting the environment variable, one also needs to modify the `read_env()` call when loading the settings. For instance ...

**settings.py**
```
env = environ.Env()
env.read_env(env.str('ENV_PATH', '.env'))
```

It seems this was identified (a long time back) as it is now better described in [this commit](https://github.com/joke2k/django-environ/blob/dc2d281e45eb41a723549e01e435ae1fe89b0a96/README.rst#multiple-env-files) which is still in the `develop` branch.

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/308) branch. Thank you for the patch, and for helping us make django-environ better. And I am sorry about the delay.
