### ISSUE TITLE
Add support for channels configuration

### ISSUE THREAD

**Issue by fkromer** [joke2k/django-environ#266]
Would be great to have support for [channel layer configuration](https://channels.readthedocs.io/en/latest/topics/channel_layers.html?highlight=configuration#configuration) in `django-environ` :smirk: The in-memory channel layer config is pretty simple. The [channel_redis config](https://github.com/django/channels_redis/#usage) one is more interesting.

**Comment by AstraLuma** [comment]
please, this is rapidly becoming extremely annoying.

**Comment by kevinrenskers** [comment]
That would be really nice to have. As I workaround I did it like this, but hopefully there's a better solution?

``` python
env = environ.Env(
    DEBUG=(bool, False),
    CI=(bool, False),
)

if env("CI"):
    CHANNEL_LAYERS = {
        "default": {"BACKEND": "channels.layers.InMemoryChannelLayer"},
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [("127.0.0.1", 6379)],
            },
        },
    }
```

**Comment by sergeyklay** [comment]
Implemented in https://github.com/joke2k/django-environ/pull/514. Thank you for contributing.
