### ISSUE TITLE
django-environ vs python-dotenv

### ISSUE THREAD

**Issue by Palisand** [joke2k/django-environ#270]
What are the differences, advantages, and disadvantage of this library and [python-dotenv](https://github.com/theskumar/python-dotenv)? I can't find any documentation regarding this.

**Comment by zufra** [comment]
https://www.untangled.dev/2020/05/31/django-environment-variables/

**Comment by karthicraghupathi** [comment]
Here is another article that compares a lot of packages providing this functionality: https://xiang.dev/python-env-vars/

I guess the biggest difference is `django-environ` also helps you cast values to a particular data type but `python-dotenv` doesn't.
