### ISSUE TITLE
Can't name env variable 'DJANGO_ENV'

### ISSUE THREAD

**Issue by PaulHarrer** [joke2k/django-environ#272]
I recognized that it's not possible to name a variable 'DJANGO_ENV'. I mean you can but it will be always 'DEVELOP' no matter what you really set it in the .env file.

Is there a way to make it work? I didn't read anything about that issue in the documentation.

**Comment by sergeyklay** [comment]
@Smort1 Could you pleas provide a minimal code to reproduce the issue?
