### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by lanshark** [joke2k/django-environ#282]
There has not been a new release since 2018, yet there is a substantial amount of work done in the develop branch.  Will any of this be released soon?

**Comment by tobiashochguertel** [comment]
Yeah, I was asking me this, too? and I think that the documentation like the example isn't really working or correct?

because it does: `import environ` ... and that looks like: https://pypi.org/project/environ/

I played also around, and delete from my `.venv/` the library `environ` -> `.venv/lib/python-3.9/site-packages/environ` and I see in pycharm that my django project does now miss the `environ` module..

I runned a `poetry update`, after I deleted the `environ` lib from the `.venv/`, and poetry told me that nothing is to update, so every is fine, No recreating of `environ` lib.

so I think there is something complete wrong?!

**Comment by joke2k** [comment]
Hi guys
thank you for writing.

Yes, I definitely make a new release as soon as possible.
If you want to help me, I'll appreciate it.

@tobiashochguertel sorry but the package is working for a long time... maybe there is something in your configuration.
Open a new issue please.

**Comment by lanshark** [comment]
What can I do to help?  Be happy to!

**Comment by nniehoff** [comment]
Any updates here?  We'd love to use django-environ but are a little leary because it's been a while since a release.

**Comment by sergeyklay** [comment]
@joke2k Could you please take a look by any chance? Maybe, if you don't have time for this, you could give someone the appropriate rights?

**Comment by joke2k** [comment]
> @joke2k Could you please take a look by any chance? Maybe, if you don't have time for this, you could give someone the appropriate rights?

@sergeyklay if you, or somebody else are interested, please contact me on discord python. Let's talk about that

**Comment by 1oglop1** [comment]
@joke2k, @sergeyklay 
I noticed that @sergeyklay has made his own fork, just to release the features.
I wonder if you guys did not manage to chat together. 
As an alternative, we can try to contact https://jazzband.co/ for the maintenance of the project.
There may be a similar organisation for Django specific projects.

**Comment by sergeyklay** [comment]
I contacted @joke2k several times in Discord. But unfortunately, he was so busy that he did not answer me anything (except a greeting). I waited a week or so and wrote to him again. The reply was the same (nothing). Third time, I waited a week and wrote to him again. The same.

I'm maintaining several projects that depend on django-environ. This is why it is important for me to timely accept patches and keep the library up to date. This is why I decided to create and maintain my own fork called django-environ-2.

**Comment by joke2k** [comment]
@sergeyklay if you check discord you can see that I replied to you on the 21st of June and today...

**Comment by sergeyklay** [comment]
Status update for the community: We contacted with @joke2k (finally!) and successfully discussed all the details. We came to a general agreement that I become one of the maintainer of django-environ. I will take up my duties in the coming days, as soon as I get the necessary rights.

**Comment by sergeyklay** [comment]
v0.5.0 version was released a few minutes ago:

- https://github.com/joke2k/django-environ/releases/tag/v0.5.0
- https://pypi.org/project/django-environ/0.5.0/
