### ISSUE TITLE
Can't use WindowPath in read_env() method

### ISSUE THREAD

**Issue by Moon-developer** [joke2k/django-environ#286]
Using `pathlib`'s `Path` object to generate a path to a file on windows can't get read by the `read_env` method.

Before:
```
env_file = Path.joinpath(BASE_DIR, ".env")
if Path(env_file).is_file():
    env.read_env(env_file)
```
After:
```
env_file = Path.joinpath(BASE_DIR, ".env")
if Path(env_file).is_file():
    env.read_env(env_file.as_posix()) # Work around
```

Wondering if library can be updated to handle `WindowsPath` object too?

**Comment by sergeyklay** [comment]
This is resolved in [`develop`](https://github.com/joke2k/django-environ/pull/313) branch. Thank you for the report, and for helping us make django-environ better. And I am sorry about the delay.
