### ISSUE TITLE
Could we get a new release

### ISSUE THREAD

**Issue by jsatt** [joke2k/django-environ#292]
It's been a couple years since the last release and there have been many PRs merged and the version even bumped to 1.0.0. Any way we can get a release so we can use these updated features? I need #211 in particular.

**Comment by shayneoneill** [comment]
Or at least put up a note saying the package isn't useable rigt now. I've spent hours trying to track down a problem, only to discovered its been fixed in a version that hasnt been released yet.

**Comment by sergeyklay** [comment]
For those who can't wait features from `develop` branch to be released:

**`requirements.txt`:**
```txt
git+https://github.com/joke2k/django-environ@develop
```

**`setup.py`:**
```py
INSTALL_REQUIRES = [
    # ...
    'django-environ>=0.4.5',
    # ...
]

DEPENDENCY_LINKS = [
    # ...
    'git+https://github.com/joke2k/django-environ@develop#egg=django-environ-0.4.5',
    # ...
]

if __name__ == '__main__':
    setup(
        # ...
        install_requires=INSTALL_REQUIRES,
        dependency_links=DEPENDENCY_LINKS,
    )
```

**Comment by RyanBalfanz** [comment]
> Or at least put up a note saying the package isn't useable rigt now. I've spent hours trying to track down a problem, only to discovered its been fixed in a version that hasnt been released yet.

What problem is that?

**Comment by nniehoff** [comment]
This is a dup of #282

**Comment by shayneoneill** [comment]
> > Or at least put up a note saying the package isn't useable rigt now. I've spent hours trying to track down a problem, only to discovered its been fixed in a version that hasnt been released yet.
> 
> What problem is that?

It wasn't finding the .env file, latest version of Django, or was ignoring it. Moving to a version directly from devel on this repo fixed it instantly

**Comment by sergeyklay** [comment]
Close in favour of #282
