### ISSUE TITLE
urlparse, urlsplit confused when password includes fragment (#), query (?)

### ISSUE THREAD

**Issue by 1oglop1** [joke2k/django-environ#298]
Hi,
I just got bitten by this bug in python https://bugs.python.org/issue18140 which effectively affects `django-environ` that depends on `urlparse`.

Example:
`.env` file
```
DATABASE_URL="postgres://AuserD:se#ret@localhost:5432/database?conn_max_age=500"
```
`settings.py` file
```
print(env.db('DATABASE_URL'))
```

results in: 
```
  File "/home/<user>/.pyenv/versions/3.8.2/lib/python3.8/urllib/parse.py", line 174, in port
    raise ValueError(message) from None
ValueError: Port could not be cast to integer value as 'se'
```

This issue has been fixed in `python 3.10`.

Until then, the workaround is to use `urllib.parse.quote` on the secret value.

```
import urllib

print(urllib.parse.quote('se#ret'))  # se%23ret
```

resulting in url like this `postgres://AuserD:se%23ret@localhost:5432/database?conn_max_age=500`

then 

```
print(env.db('DATABASE_URL'))
```
gives an expected result

```
{'NAME': 'database', 'USER': 'AuserD', 'PASSWORD': 'se#ret', 'HOST': 'localhost', 'PORT': 5432, 'CONN_MAX_AGE': 500, 'OPTIONS': {}, 'ENGINE': 'django.db.backends.postgresql'}
```

**Comment by 1oglop1** [comment]
Also closing this issue since I found workaround and it will be fixed with the latest Python version.

**Comment by sergeyklay** [comment]
@1oglop1 Please take a look at this answer https://github.com/joke2k/django-environ/issues/288#issuecomment-908320933

**Comment by 1oglop1** [comment]
@sergeyklay Thanks. I think it's a good enough solution to mention this in docs!
I got caught by that by surprise. Now it would be nice if we could combine it with #127. 
It's not very compatible with `pg_*` tools because some of them support URL but some require each part as an argument.
However, all `pg_*` tools read `.pgpass`.
https://www.postgresql.org/docs/13/libpq-envars.html

I'd welcome any suggestion that makes the configuration more sensible.
