### ISSUE TITLE
Support for django-redis

### ISSUE THREAD

**Issue by tarkatronic** [joke2k/django-environ#32]
In the CACHE_SCHEMES, both `redis` and `rediscache` map to `redis_cache.cache.RedisCache`, referring to django-redis-cache. For comparison sake, in the django-cache-url project, `redis` and `hiredis` both map to `django_redis.cache.RedisCache`, referring to django-redis.

Is there a reason that, in django-environ, one of these (or perhaps a new scheme) couldn't map to `django_redis.cache.RedisCache`?

Or is there a particularly strong reason for preferring django-redis-cache over django-redis?

**Comment by joke2k** [comment]
merged in fef7824

**Comment by joke2k** [comment]
Hi, please check my PR to resolve this question.

Thank you for reporting... honestly, I didn't think there were more libraries that support redis in django.
