### ISSUE TITLE
ModuleNotFoundError: No module named 'environ' :: With celery and supervisor

### ISSUE THREAD

**Issue by Yogeshddjango** [joke2k/django-environ#324]
When Celery run  background at that time I get 
ModuleNotFoundError: No module named 'environ', 
can any guide me how to setup this in production

**Comment by sergeyklay** [comment]
@Yogeshddjango Could you please provide a minimal code to reproduce?

**Comment by Yogeshddjango** [comment]
from __future__ import absolute_import, unicode_literals
import os
import environ

from celery import Celery
from django.conf import settings
from celery.schedules import crontab
# set the default Django settings module for the 'celery' program.

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

env = environ.Env()
environ.Env.read_env(env_file=os.path.join(BASE_DIR, '.env'))

os.environ.setdefault('DJANGO_SETTINGS_MODULE', env('DJANGO_SETTINGS_MODULE'))

app = Celery('tasks', backend='redis://localhost:6379/0', broker='redis://localhost:6379/0')
#app.config_from_object('django.conf:settings')

app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)
app.conf.timezone = 'America/Mexico_City'

app.conf.beat_schedule = {
    'send_inspection_email_at_midnight': {
        'task': 'inspection.tasks.send_inspection_email_at_midnight',
        'schedule': crontab(hour=0, minute=0),
        'args': (),
    },
    'task_manager_inspection_report_reminder': {
        'task': 'inspection.tasks.task_manager_inspection_report_reminder',
        'schedule': crontab(minute=0),
        'args': (),
    },
    'task_manager_review_remider': {
        'task': 'inspection.tasks.task_manager_review_remider',
        'schedule': crontab(minute=0),
        'args': (),
    },
    'task_manger_outstanding_repair_reminder': {
        'task': 'inspection.tasks.task_manger_outstanding_repair_reminder',
        'schedule': crontab(minute=0),
        'args': (),
    },
    
    
}

**Comment by sergeyklay** [comment]
It is easy to verify django-environ is installed using the following approach _inside your Celery app_:
```py
from pkg_resources import working_set

installed_packages = ("%s==%s" % (i.key, i.version) for i in working_set)
installed_packages_list = sorted(installed_packages)

print(installed_packages_list)
```

Could you please try something like that to ensure django-environ is installed?

**Comment by Yogeshddjango** [comment]
> It is easy to verify django-environ is installed using the following approach _inside your Celery app_:
> 
> ```python
> from pkg_resources import working_set
> 
> installed_packages = ("%s==%s" % (i.key, i.version) for i in working_set)
> installed_packages_list = sorted(installed_packages)
> 
> print(installed_packages_list)
> ```
> 
> Could you please try something like that to ensure django-environ is installed?

Yes, I tried and I got this 

['amqp==5.0.6', 'anyjson==0.3.3', 'arabic-reshaper==2.1.1', 'asgiref==3.3.1', 'beautifulsoup4==4.9.3', 'billiard==3.6.4.0', 'boto3==1.17.40', 'botocore==1.20.40', 'cached-property==1.5.2', 'celery==5.1.2', 'cffi==1.14.4', 'click-didyoumean==0.0.3', 'click-plugins==1.1.1', 'click-repl==0.1.6', 'click==7.1.2', 'cryptography==3.3.1', 'cssutils==2.3.0', 'defusedxml==0.7.1', 'diff-match-patch==20200713', 'django-autoslug==1.9.8', 'django-bootstrap4==2.3.1', 'django-constance==2.8.0', 'django-crispy-forms==1.11.0', 'django-environ==0.4.5', 'django-filter==2.4.0', 'django-formtools==2.2', 'django-import-export==2.5.0', 'django-inlinecss==0.3.0', 'django-s3direct==1.1.8', 'django-ses==1.0.3', 'django-storages==1.11.1', 'django-widget-tweaks==1.4.8', 'django==3.1.5', 'easy-thumbnails==2.7.1', 'et-xmlfile==1.0.1', 'future==0.18.2', 'html5lib==1.1', 'importlib-metadata==2.1.1', 'jmespath==0.10.0', 'kombu==5.1.0', 'markuppy==1.14', 'numpy==1.19.5', 'odfpy==1.4.1', 'openpyxl==3.0.7', 'pillow==8.1.0', 'pip==21.1.3', 'pipi==1.0.1', 'prompt-toolkit==3.0.18', 'psycopg2-binary==2.8.6', 'pycparser==2.20', 'pynliner==0.8.0', 'pyopenssl==19.1.0', 'pypdf2==1.26.0', 'python-bidi==0.4.2', 'python-dateutil==2.8.1', 'pytz==2020.5', 'pyyaml==5.4.1', 'redis==3.2.0', 'reportlab==3.5.59', 's3transfer==0.3.6', 'setuptools==57.0.0', 'six==1.15.0', 'soupsieve==2.1', 'sqlparse==0.4.1', 'tablib==3.0.0', 'urllib3==1.26.4', 'vine==5.0.0', 'wcwidth==0.2.5', 'webencodings==0.5.1', 'wheel==0.36.2', 'whitenoise==5.2.0', 'xhtml2pdf==0.2.5', 'xlrd==2.0.1', 'xlwt==1.3.0', 'zipp==3.4.0']

**Comment by sergeyklay** [comment]
What is the output of `help('modules environ')` inside the celery app?

**Comment by Yogeshddjango** [comment]
> What is the output of `help('modules environ')` inside the celery app?

Sorry for late reply..
I put you codes in production and I got this, django-environ not installed, when I run supervisor

['amqp==5.0.6', 'anyjson==0.3.3', 'arabic-reshaper==2.1.1', 'asgiref==3.3.1', 'beautifulsoup4==4.9.3', 'billiard==3.6.4.0', 'boto3==1.17.40', 'botocore==1.20.40', 'cached-property==1.5.2', 'celery==5.1.2', 'cffi==1.14.4', 'click-didyoumean==0.0.3', 'click-plugins==1.1.1', 'click-repl==0.1.6', 'click==7.1.2', 'cryptography==3.3.1', 'cssutils==2.3.0', 'defusedxml==0.7.1', 'diff-match-patch==20200713', 'django-bootstrap4==2.3.1', 'django-crispy-forms==1.11.0', 'django-filter==2.4.0', 'django-formtools==2.2', 'django-import-export==2.5.0', 'django-inlinecss==0.3.0', 'django-s3direct==1.1.8', 'django-ses==1.0.3', 'django-storages==1.11.1', 'django-widget-tweaks==1.4.8', 'django==3.1.5', 'easy-thumbnails==2.7.1', 'et-xmlfile==1.0.1', 'future==0.18.2', 'html5lib==1.1', 'importlib-metadata==2.1.1', 'jmespath==0.10.0', 'kombu==5.1.0', 'markuppy==1.14', 'numpy==1.19.5', 'odfpy==1.4.1', 'openpyxl==3.0.7', 'pillow==8.1.0', 'pip==21.0.1', 'pipi==1.0.1', 'prompt-toolkit==3.0.18', 'psycopg2-binary==2.8.6', 'pycparser==2.20', 'pynliner==0.8.0', 'pyopenssl==19.1.0', 'pypdf2==1.26.0', 'python-bidi==0.4.2', 'python-dateutil==2.8.1', 'pytz==2020.5', 'pyyaml==5.4.1', 'redis==3.2.0', 'reportlab==3.5.59', 's3transfer==0.3.6', 'setuptools==52.0.0', 'six==1.15.0', 'soupsieve==2.1', 'sqlparse==0.4.1', 'tablib==3.0.0', 'urllib3==1.26.4', 'vine==5.0.0', 'wcwidth==0.2.5', 'webencodings==0.5.1', 'wheel==0.36.2', 'whitenoise==5.2.0', 'xhtml2pdf==0.2.5', 'xlrd==2.0.1', 'xlwt==1.3.0', 'zipp==3.4.0']

Here is a list of modules whose name or summary contains 'environ'.
If there are any, enter a module name to get more help.

venv - Virtual environment (venv) package for Python. Based on PEP 405.
_virtualenv - Patches that are applied at runtime to the virtual environment
django.core.mail.backends.locmem - Backend for test environment.
numpy.distutils.fcompiler.environment 
pip._internal.build_env - Build Environment used for isolation during sdist building
pip._vendor.distlib.markers - Parser for the environment markers micro-language defined in PEP 508.
pip._vendor.pep517.envbuild - Build wheels/sdists by installing build deps to a temporary environment.
pip._vendor.urllib3.contrib._appengine_environ - This module provides means to detect the App Engine environment.
urllib3.contrib._appengine_environ - This module provides means to detect the App Engine environment.

**Comment by sergeyklay** [comment]
> I put you codes in production and I got this, django-environ not installed, when I run supervisor

The problem could occur due to the following reasons:

- You're using virtual environment, but you installed module **outside** the virtual environment
- You're **not using virtual environment**, but you installed module inside the virtual environment
- You're using one virtual environment to install django-environ, and **another** virtual environment  to run celery app

**Comment by Yogeshddjango** [comment]
@sergeyklay Thanks for the help I found the issue, I created an executable file in the environment for running celery and also write code to activate env, the path of activating ENV is wrong that's why it's creating an issue.

**Comment by sergeyklay** [comment]
You're welcome :)
