### ISSUE TITLE
Trailing slash breaks `pymemcached`

### ISSUE THREAD

**Issue by WhyNotHugo** [joke2k/django-environ#337]
When using `pymemcached`, a trailing slash in the URL breaks. This works:

    export CACHE_URL="pymemcache://memcached:11211?key_prefix=ci"

But this fails with a `ConnectionRefusedError: [Errno 111] Connection refused`:

    export CACHE_URL="pymemcache://memcached:11211/?key_prefix=ci"

**Comment by sergeyklay** [comment]
Thank you for reporting. I'll try to sort out ASAP.
