### ISSUE TITLE
Version 0.8.0 generates "Invalid line" error on blank lines in file

### ISSUE THREAD

**Issue by KenWhitesell** [joke2k/django-environ#340]
A blank line in an env file causes Django's manage.py to show "Invalid line" messages. This occurs even if no sub-command is specified.

An error is also thrown on a line beginning with an octothorpe ("#") - something that we use to comment those files.

The Usage docs don't specifically state that these are legal lines. However, the example further down on that page uses them within the example.

**Comment by sergeyklay** [comment]
Fixed in [`develop`](https://github.com/joke2k/django-environ/pull/339) branch. I'll release a hotfix ASAP. Thank you for reporting.
