### ISSUE TITLE
env file cannot have space around equals sign

### ISSUE THREAD

**Issue by robvdl** [joke2k/django-environ#35]
I found out that I cannot do this in the .env file:

SOMEVAR = foo

but this works fine:

SOMEVAR=foo

is this by design? maybe a quick mention of this in the README because it confused me for a bit, I thought settings weren't being read, until I removed the spaces around the = sign.

**Comment by Arlefreak** [comment]
This is how you normally declare environment variables on bash

**Comment by joke2k** [comment]
Yeah @robvdl this is the way to declare variables in .env file.
It is a convention, maybe I've to write about in README file.

Thank you anyway

**Comment by robvdl** [comment]
Thought this was closed already, closing it now..
