### ISSUE TITLE
Syncing the .env file with the defined environment variables

### ISSUE THREAD

**Issue by amartya-dev** [joke2k/django-environ#353]
I want to use a hybrid of both approaches, I should either be able to dump all the environment variables in the env file or set them manually as environment variables and we should be able to pick it up from either place when using django-environ,

Is this behavior possible with the current version? 

Reasons:
- We can keep some aspects of our application configurable and supply environment variables to the remote instance instead of changing the env file every time
- This will be especially helpful when using docker, we would be able to supply environment variables directly using the Dockerfile and that should reflect accordingly.
- This might help in case we need to change some properties "on the fly" i.e. modify some aspects by directly changing the env variables instead of re-packaging and re-deploying the entire application

**Comment by sergeyklay** [comment]
Are you want to be able to overwrite the .env file? Did I understand you correctly? If so, then there is no such possibility now. In any case, it is not clear to me why this might be needed. OS environment variables always take precedence over env-file variables.

**Comment by amartya-dev** [comment]
No I don't want to overwrite the env file, I was just wondering if the env variables set on the kernel take precedence over what we might read from the file, and as that is the case here, I think we're good :) 

Thank you very much for answering this

**Comment by sergeyklay** [comment]
Yes, the env variables set on the OS take precedence:
```sh
# command line
$ export DJANGO_ADMINS="Serghei <egrep@pm.me>,"
```

```sh
# .env file
DJANGO_ADMINS="Blake <blake@cyb.org>, Alice Judge <alice@cyb.org>"
```

```py
# test
from environ import environ

env = environ.Env()
env.read_env(env_file='.env')
print(env('DJANGO_ADMINS')). # 'Serghei <egrep@pm.me>,'
```


If you want variables set within your env files to take higher precidence than an existing set environment variable, use the `overwrite=True` argument of `read_env`. For example:

```py
from environ import environ

env = environ.Env()
env.read_env(env_file='.env', overwrite=True)
print(env('DJANGO_ADMINS'))
# 'Blake <blake@cyb.org>, Alice Judge <alice@cyb.org>'
```
