### ISSUE TITLE
Feature request: support default redis backend

### ISSUE THREAD

**Issue by glasnt** [joke2k/django-environ#356]
As of Django 4.0, there is now core support for the [redis backend](
https://docs.djangoproject.com/en/4.0/topics/cache/#redis).

Currently, `django-environ` detects uses package inspection to work out which redis backend to use (in [environ/compat.py](https://github.com/joke2k/django-environ/blob/main/environ/compat.py#L35)), which uses `redis_cache` if detected, or it defaults to `django_redis`.

I think this package should default to using the core backend if using Django 4.0 or above/ 

(I am working on this in a branch on my fork. Pull Request shortly.)

**Comment by glasnt** [comment]
TIL while writing tests that `Env.cache_url_config` exists, and so there is a workaround for now (which I couldn't find any explicit documentation for:

```python
CACHES = {
    'default': env.cache_url('REDIS_URL', backend='django.core.cache.backends.redis.RedisCache')
}
```

Also looking through the tests, I realise supporting Django 4 is not something this package currently does, and there would be copious test changes to ensure Django 4 support in the first place. 

For reference, here is the base code I suggest. This based on the logic that it should detect for a package before detecting for a Django version, being installing a package is an active choice on the user's part.

```python
# environ/compat.py

# back compatibility with redis_cache package
if find_loader('redis_cache'):
    REDIS_DRIVER = 'redis_cache.RedisCache'
# default to built-in redis backend if availabler
elif DJANGO_VERSION is not None and DJANGO_VERSION < (4, 0):
    REDIS_DRIVER='django.core.cache.backends.redis.RedisCache'
else:
    REDIS_DRIVER = 'django_redis.cache.RedisCache'

```

**Comment by glasnt** [comment]
It may also make sense to use a new scheme for the core redis, much like how there's `memcache` and `pymemcache`. That should help more with backwards compat.

**Comment by xblitz** [comment]
good job, any chance to create a Pull-Request for this?

**Comment by sergeyklay** [comment]
Implemented in https://github.com/joke2k/django-environ/pull/397. Thank you for contributing!
