### ISSUE TITLE
*** @sergeyklay is afk due to war in Ukraine ***

### ISSUE THREAD

**Issue by joke2k** [joke2k/django-environ#366]
The actual maintainer of django-environ, @sergeyklay, is not available to handle new issues or pull requests. 

We all would like to think that he is well but busy going to a safe place during this war.
I personally tried to contact him throught all channels but he didn't reply yet.

I'll keep you updated with this issue and meanwhile, I try to help with issues and PR.

🙏

**Comment by sergeyklay** [comment]
Ok, I have access to my laptop. The war continues, but I'm safe (although I don't have as much free time as before)
