### ISSUE TITLE
"Invalid line" error when line starts with spaces and then a comment follows

### ISSUE THREAD

**Issue by wimfeijen** [joke2k/django-environ#403]
We use comments, nested with 4 spaces. This works fine in environ 0.4.5 , but now generates an error in environ 0.9.0:

> Invalid line:     # Domain, without prefix ('www.') and suffix ('.nl'/'.com')

in both .env and the error message, 4 spaces preceed the hashtag. Sorry, I did not succeed in finding the right way to enter four spaces in this edit field.

Thanks for looking into this!

**Comment by sergeyklay** [comment]
@wimfeijen Could you please provide a small .env to reproduce this issue?

**Comment by lvanderree** [comment]
I tried to fix this in https://github.com/joke2k/django-environ/pull/475

**Comment by sergeyklay** [comment]
This was fixed in #475 thanks to @lvanderree. We'll include this in the next release. Thank you for the report, and for helping us make django-environ better.
