### ISSUE TITLE
0.9.0 yields bogus results for Redis

### ISSUE THREAD

**Issue by WhyNotHugo** [joke2k/django-environ#409]
`env.cache()` yields results with `django_redis.cache.RedisCache`, on Django 4.0, whereas it should be returning `django.core.cache.backends.redis.RedisCache`.

I see this was fixed in develop via https://github.com/joke2k/django-environ/pull/397, but that was merged AFTER 0.9.0 was released, and 0.9.0 was marked as compatible with Django 4+.

It seems the order of things got mixed up in the release process.

Can we have a 0.9.1 bugfix release with this change? After upgrading to Django 4.0 I'm trying to switch to Redis as a cache, but this is a blocker.

**Comment by sergeyklay** [comment]
@WhyNotHugo Thank you for the report, and for helping make django-environ better. Could you help me by sending a path? I just don't have the bandwidth for this :)

**Comment by sergeyklay** [comment]
I'll try to release next version ASAP, thank you for the report, and for helping us make django-environ better.

**Comment by jeriox** [comment]
Any news on this? Would love to use the new backend as well

**Comment by jeriox** [comment]
hey @sergeyklay, any chance you could release a new version?

**Comment by sergeyklay** [comment]
I apologize for the long response. I'm a little overwhelmed these days. It's been a long time since I've commented on this issue but I just wanted to mention that it's still on my queue.

**Comment by jeriox** [comment]
No worries, thanks for your work!
If i understood the original text of the issue correctly, the implementation is already merged and the only thing that is missing is a release of a new version, so maybe that makes it easier for you :)

**Comment by sergeyklay** [comment]
django-environ v0.10.0 is released on pypi: https://pypi.org/project/django-environ/0.10.0/


Thank you for opening issue and I'm sorry for the delay.

**Comment by jeriox** [comment]
thank you very much!
