### ISSUE TITLE
`interpolate` flag functionality is not implemented

### ISSUE THREAD

**Issue by r4victor** [joke2k/django-environ#415]
I did `SECRET_KEY = env('DJANGO_SECRET_KEY')` and got the error:

```
django.core.exceptions.ImproperlyConfigured: Set the a&d3*0k#skh)!5o)$))zz9&%hr@-akid5zh--05ei790+wn0$r environment variable
```

This is becuase my `DJANGO_SECRET_KEY` starts with the dollar sign: 

```
DJANGO_SECRET_KEY="$a&d3*0k#skh)!5o)$))zz9&%hr@-akid5zh--05ei790+wn0$r"
```

There was a number of issues for this problem: #284, #60, #271.

Eventually, #333 somewhat solved the issue by allowing to escape the dollar sign. But this is not the best approach for generated values such as secret keys. The better option would be an ability to disable interpolation altogether. Ideally by default since the behaviour is unexpected.

Interestingly, the `interpolation` flag is described in the docs: https://django-environ.readthedocs.io/en/latest/tips.html?highlight=Proxied%20Values#proxy-value. BUT it's not implemented! [This commit ](https://github.com/joke2k/django-environ/commit/f8c8a1ff50109e1b6de99e3f6ad51b326a794392) introduced the doc. Apparently, the implementation (#145) was not merged and closed in favor of #333. I don't know why. #145 seems like a proper solution.

**Comment by ebridges** [comment]
It does appear to work albeit in a limited fashion, e.g. here's the example from the docs, plus the use case I'm looking for (embedding db credentials into a db url).  The example from the docs works but the URL case does not.  Given that the word `interpolate` only occurs in the documentation in the code base, it seems that it's relying on some kind of implicit behavior.

```
import environ

TEST_ENV='test.env'

with open(TEST_ENV, 'w') as f:
    f.write('FOO=bar\n')
    f.write('BAR=$FOO\n')
    f.write('URL=abc://$FOO\n')

env = environ.Env(interpolate=True)
env.read_env(TEST_ENV)

bar = env('BAR')
url = env('URL')

print(f'bar: {bar}, url: {url}')
```

**Comment by r4victor** [comment]
@ebridges, `interpolate=True` seems to work because interpolation is a default behaviour. Try calling `environ.Env()` or `environ.Env(interpolate=False)` and you'll get the same result.

**Comment by ebridges** [comment]
Yes I agree.  Because I needed this functionality I have simply switched to use `python-dotenv` which offers that.

**Comment by ThalusA** [comment]
This feature will really be never implemented ?

**Comment by daggaz** [comment]
This one just tripped me up too. Any chance the attached PR will be merged soon? In my case, I'm generating and setting a django secret key, and it ended up randomly starting with `$`, which caused me bit of confusion...

**Comment by sergeyklay** [comment]
This is implemented in https://github.com/joke2k/django-environ/pull/419. Thank you for the  report.
