### ISSUE TITLE
Any plan to support embedded variables?

### ISSUE THREAD

**Issue by sylvainletourneau** [joke2k/django-environ#421]
I was wondering if there has been discussions/plans to support embedded variables in .env file.  For example,
```
# .env file with embedded variables
LIB_PATH=/home/username/.lib
GDAL_LIBRARY_PATH=${LIB_PATH}/osgeo/gdal304.dll
GEOS_LIBRARY_PATH=${LIB_PATH}/osgeo/geos_c.dll
```
I got used to the ${VAR_NAME} syntax as it is supported by docker-compose and python-dotenv among others.   It would be great to get the same support in django-environ. I'm aware of the interpolate feature which covers a more limited use case.

Would that be useful to anyone else?

**Comment by fdemmer** [comment]
This is already supported, but with different synthax: https://django-environ.readthedocs.io/en/latest/tips.html?highlight=proxy#proxy-value

Although it might not work as expected, there were a number of issues discussing it: 
- https://github.com/joke2k/django-environ/issues?q=is%3Aissue+proxy+is%3Aclosed
- and an open one: https://github.com/joke2k/django-environ/issues/415

**Comment by sylvainletourneau** [comment]
The link provided refers to the proxy feature.  This feature allows us to associate a specific value to various variable names.  I'm looking for a more generic solution in which the variable definition can include one or more other variables along with additional text.   This would allow us to re-use the content of one or more variables to create a new variable, while the current implementation only allow us to duplicate a variable.



# Current proxy feature

VAR_1=bar

VAR_2=$VAR_1

VAR_3=$VAR_1



# Desired feature

VAR_1=prod

VAR_2=my_app_name

APP_ROOT_DIR=/opt/${VAR_1}/${VAR_2}    # /opt/prod/my_app_name

APP_LIB_DIR=/opt/${VAR_1}/${VAR_2}/lib   # /opt/prod/my_app_name/lib










---- On Tue, 11 Oct 2022 03:20:41 -0400 Florian Demmer ***@***.***> wrote ---





This is already supported, but with different synthax: https://django-environ.readthedocs.io/en/latest/tips.html?highlight=proxy#proxy-value

Although it might not work as expected, there were a number of issues discussing it:

https://github.com/joke2k/django-environ/issues?q=is%3Aissue+proxy+is%3Aclosed

and an open one: https://github.com/joke2k/django-environ/issues/415

**Comment by sergeyklay** [comment]
Values that being with a $ may be interpolated. Pass interpolate=True to environ.Env() to enable this feature:

```python
import environ

env = environ.Env(interpolate=True)

# BAR=FOO
# PROXY=$BAR
#
# LIB_PATH=/home/username/.lib
# GDAL_LIBRARY_PATH=$LIB_PATH/osgeo/gdal304.dll


>>> print env.str('PROXY')
FOO

>>> print(env.str('LIB_PATH'))
/home/username/.lib

>>> print(env.str('GDAL_LIBRARY_PATH'))
/home/username/.lib/osgeo/gdal304.dll

>>> from environ import __version__
>>> print(__version__)
0.10.0
```
