### ISSUE TITLE
help needed?

### ISSUE THREAD

**Issue by andreasnuesslein** [joke2k/django-environ#426]
hello @joke2k 

I would like to offer help, because we heavily use this package and we would be interested in its further development. 

It seems like right now you might not have so much time, hence: let me know if I can assist.

cheers

**Comment by sergeyklay** [comment]
Hi Andreas,

Thank you for your feedback and offer of help. It's really appreciated. You're right, we're a little overloaded with work and household chores at the moment, so we don't have much time left for the project. In any case, the project continues to be supported, albeit less actively. If you want to help, start here:
- https://github.com/joke2k/django-environ/issues

A few words about our standards:
- Backward compatibility MUST NOT be broken unless it is specified in advance and a migration plan has been developed
- Any changes in the project logic SHOULD be documented
- Any changes in the project logic MUST be covered by change log
- Any changes in the project logic MUST be covered by tests

Thank you for the your words, and for offering help to make this project better.
