### ISSUE TITLE
Support for new default redis driver in Django 4.0+

### ISSUE THREAD

**Issue by aixcyi** [joke2k/django-environ#434]
## Problem

New Redis driver `django.core.cache.backends.redis.RedisCache` was added in Django 4.0, but `django-environ` always use `django_redis.cache.RedisCache` in default.

## Resolution

Change source code on line 29 in `./environ/compat.py` from

```Python
if find_loader('redis_cache'):
    REDIS_DRIVER = 'redis_cache.RedisCache'
else:
    REDIS_DRIVER = 'django_redis.cache.RedisCache'
```

to

```Python
if DJANGO_VERSION is not None and DJANGO_VERSION >= (4, 0):
    REDIS_DRIVER = 'django.core.cache.backends.redis.RedisCache'
elif find_loader('redis_cache'):
    REDIS_DRIVER = 'redis_cache.RedisCache'
else:
    REDIS_DRIVER = 'django_redis.cache.RedisCache'
```

However, it may be not a good idea for other user which want to use `django_redis` in Django 4.0+ by default.

## Reference

[BACKEND - CACHES | Django Settings](https://docs.djangoproject.com/en/4.1/ref/settings/#backend)

**Comment by sergeyklay** [comment]
The fix in the develop branch and will be released ASAP.

For details see:
- https://github.com/joke2k/django-environ/commit/7ee07abaae55732f5ea52c8a65621626f77e9198
- https://github.com/joke2k/django-environ/commit/4ef047f2258255b05720c9fbc2440bc504daf893
- https://github.com/joke2k/django-environ/commit/c1b7034bbd54c548f48f8d19c882c772a29f394b
