### ISSUE TITLE
Default Django Redis in 0.10.0

### ISSUE THREAD

**Issue by legau** [joke2k/django-environ#449]
Hi, 
In 0.10.0 the core Redis driver implemented in Django 4 `'django.core.cache.backends.redis.RedisCache'` has been made the default Redis driver.
This causes a regression django-redis users, the core driver is less extensive than django-redis and as such I think it should be prioritized if it is installed. This library has no reason to be here if not to be used as the main django driver so that would make more sense imo.

I can make a quick PR to fix this if you agree.

**Comment by sergeyklay** [comment]
Yes, if you can make a patch that would be great! Thank you

**Comment by sergeyklay** [comment]
The fix is already in development branch (see https://github.com/joke2k/django-environ/pull/450 for more) and we will try to release it as soon as possible. Thank you for pointing out this annoying regression bug.
