### ISSUE TITLE
`cache_url` doesn't handle backend properly.

### ISSUE THREAD

**Issue by RemiDesgrange** [joke2k/django-environ#464]
I have no idea if it's bug or a feature:

let's say I have 2 env var:
```
DEFAULT_COMPONENT_URL=dummycache://
DEFAULT_COMPONENT_BACKEND=dumy
```

in `settings.py`

```python
import environ
from pathlib import Path

BASE_DIR = Path(environ.Path())
env = environ.FileAwareEnv(
    interpolate=True,
)
environ.Env.read_env(BASE_DIR / ".env")
CACHES = {
    "default": env.cache_url(
        "DEFAULT_CACHE_URL",
        f"redis://redis:6379/1",
        backend=env.str("DEFAULT_CACHE_BACKEND", "django_redis.cache.RedisCache"),
    )
}
```

 the backend is set here https://github.com/joke2k/django-environ/blob/8874288ac11bc70fa491439d52a4c307f9388aea/environ/environ.py#L629 to `django.core.cache.backends.dummy.DummyCache`.

But the `backend`key is reset to the default value 44 lines later here https://github.com/joke2k/django-environ/blob/8874288ac11bc70fa491439d52a4c307f9388aea/environ/environ.py#L673-L674

no idea if this is intentional or not. I the fix is only removing the `if backend` line I'll be happy to submit a PR.

**Comment by sergeyklay** [comment]
Hi @RemiDesgrange,

Thank you for bringing this issue to our attention. To better understand the problem and evaluate your proposed solution, could you please provide a test case that reproduces the issue? A test that highlights the current problems and needs would be particularly helpful.

**Comment by RemiDesgrange** [comment]
Ok, in what form this solution should be provided ? The `settings.py` I gave can be executed in a shell (without even django). Do you need a test case with pytest etc... ?

Thx.

**Comment by sergeyklay** [comment]
> Ok, in what form this solution should be provided ? The `settings.py` I gave can be executed in a shell (without even django). Do you need a test case with pytest etc... ?
> 
> Thx.

Providing a unit test would be ideal

**Comment by fdemmer** [comment]
@RemiDesgrange 

in your example you mention `DEFAULT_COMPONENT_URL`. is that a typo? should it mean `DEFAULT_CACHE_URL`?

> no idea if this is intentional or not. I the fix is only removing the if backend line I'll be happy to submit a PR.

i am guessing it _is intentional_, although there is no documentation or [testcase](https://github.com/joke2k/django-environ/blob/main/tests/test_cache.py) for it.

the `backend` kwarg _should_ override the backend defermined via the "scheme" and can be used to set a specific cache backend implementation, e.g.:

```
# use 3rd party django-redis backend instead of built-in
env.cache_url("redis://redis:6379/1", backend="django_redis.cache.RedisCache")
```


A few other shortcuts support the same mechanism, like `db(engine=...)`, `email(backend=...)` or `search_url(engine=...)`.

**Comment by RemiDesgrange** [comment]
Sorry `DEFAULT_CACHE_URL` it is. `DEFAULT_COMPONENT_URL` is indeed a typo.

Thanks for the clarification.
