### ISSUE TITLE
`env.dict()` splits on all separators rather than just first 

### ISSUE THREAD

**Issue by hrafnthor** [joke2k/django-environ#471]
### The issue at hand

When parsing a complex dict format as per the instructions found [here](https://django-environ.readthedocs.io/en/latest/tips.html#complex-dict-format) the `Env.parse_value()` method splits on every separator, causing issues with fields that contain the separator in their value section.

As an example, observe this environment variable containing options values for setting schema values for a PostgreSQL database connection:

```shell
DB_OPTIONS="options=-c search_path=<schema>;"
```

When parsed with `env.dict('DB_OPTIONS', cast={'value': str}, default={})` the resulting dictionary cuts off part of the value:

```python
 { 'options': '-c search_path' }
```
### Possible workaround

Trying to use `env.dict('DB_OPTIONS', cast=dict, default={})` results in the value being preserved, however the `;` separator is left behind (which causes this particular option not to function). 

```python
 { 'options': '-c search_path=<schema>;' }
```

### Proposed change

While it is possible to use the workaround mentioned above with an environment variable that uses  `,` rather than `;` as key/value separators works, I think it would make sense to add a maximum split value of 1 to relevant line in [ `Env.parse_value()`](https://github.com/joke2k/django-environ/blame/8874288ac11bc70fa491439d52a4c307f9388aea/environ/environ.py#L451) to bring the behaviour more in line with what would be expected to happen. 

The cast to `dict` line [just below](https://github.com/joke2k/django-environ/blame/8874288ac11bc70fa491439d52a4c307f9388aea/environ/environ.py#L454) already does handle this case (which is why it works as a workaround).

#### Versions

django-environ: 0.10.0

**Comment by sergeyklay** [comment]
Thank you for bringing this issue to our attention. To better understand the problem and evaluate your proposed solution, could you please provide a test case that demonstrates this issue? A test that highlights the current shortcomings would be extremely helpful. Looking forward to your input
