### ISSUE TITLE
Officially support Django 4.2 and Python 3.12 on PyPI

### ISSUE THREAD

**Issue by uri-rodberg** [joke2k/django-environ#479]
There is a `DeprecationWarning` in Python 3.12.0rc1:

`DeprecationWarning: 'pkgutil.find_loader' is deprecated and slated for removal in Python 3.14; use importlib.util.find_spec() in
stead`

**Comment by sergeyklay** [comment]
I hope this was fixed in https://github.com/joke2k/django-environ/pull/482. Thank you for the report
