### ISSUE TITLE
v0.11.0/ v0.11.1 breaks on Mac OSX

### ISSUE THREAD

**Issue by brent-cybrid** [joke2k/django-environ#493]
The following error occurs after updating to v0.11.0 (and v0.11.1) on Mac OSX.

Python version: 3.11.3
Django: 4.2.4

Stacktrace:
Traceback (most recent call last):
  File "<removed>/lib/python3.11/site-packages/environ/environ.py", line 419, in _get_value
    value = self.ENVIRON[var_name]
            ~~~~~~~~~~~~^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'wwk'

**Comment by sergeyklay** [comment]
django-environ v0.11.2 with a fix has been released, thank you for reporting

https://github.com/joke2k/django-environ/releases/tag/v0.11.2
