### ISSUE TITLE
db support for CockroachDB

### ISSUE THREAD

**Issue by stevewilliamsuk** [joke2k/django-environ#509]
I would like to propose a feature that django-eviron's `db()` parser shall support CockroachDB

[CockroachDB](https://www.cockroachlabs.com/) is a distributed quorum based database. Cockroach Labs have provided an [idiomatic driver for Django](https://github.com/cockroachdb/django-cockroachdb).

This driver does under the hood use psycopg, so in theory a postresql:// connection string could be used with `Env().db_url()` (I have not tried!) it is preferable to use the Cockroach driver as this improves resiliency and retry logic.

I am all too happy to submit the PR for this myself.

**Comment by stevewilliamsuk** [comment]
Would also add that it is worth considering support for djongo as well: https://www.mongodb.com/compatibility/mongodb-and-django#connect-django-and-mongodb-using-djongo

**Comment by sergeyklay** [comment]
Implemented in https://github.com/joke2k/django-environ/pull/511 so I close this one. Thank you contributing!
