### ISSUE TITLE
Provide wheel distribution on PyPI

### ISSUE THREAD

**Issue by edmorley** [joke2k/django-environ#53]
Please could you provide a wheel archive on PyPI alongside the standard package? http://pythonwheels.com/

Many thanks :-)

**Comment by joke2k** [comment]
Absolutely yes.
The next release will come out with wheel support ;)

**Comment by edmorley** [comment]
Sounds good - thank you :-)

**Comment by edmorley** [comment]
The latest releases are now available as wheels :-)
https://pypi.python.org/pypi/django-environ
