### ISSUE TITLE
Environment variables starting with $ cause a recursion error

### ISSUE THREAD

**Issue by chromakey** [joke2k/django-environ#60]
This SECRET_KEY declaration causes a maximum recursion depth exceeded error. (Note: I never used this secret key value anywhere since I was just starting the project)

```
SECRET_KEY = env("DJANGO_SECRET_KEY", default='$%ify^q7jg*o7(5me*g%+ae-7_1iy)gey*#eo%3c##-=1d=6mb')
```

Results in:

```
...snip...
  File "/Users/chromakey/.virtualenvs/xxxx/lib/python3.4/site-packages/environ/environ.py", line 260, in get_value
    value = self.get_value(value, cast=cast, default=default)
  File "/Users/chromakey/.virtualenvs/xxxx/lib/python3.4/site-packages/environ/environ.py", line 260, in get_value
    value = self.get_value(value, cast=cast, default=default)
  File "/Users/chromakey/.virtualenvs/xxxx/lib/python3.4/site-packages/environ/environ.py", line 249, in get_value
    value = os.environ[var]
  File "/Users/chromakey/.virtualenvs/xxxx/bin/../lib/python3.4/os.py", line 630, in __getitem__
    value = self._data[self.encodekey(key)]
RuntimeError: maximum recursion depth exceeded
```

This however, causes no error:

```
SECRET_KEY = env("DJANGO_SECRET_KEY", default='%ify^q7jg*o7(5me*g%+ae-7_1iy)gey*#eo%3c##-=1d=6mb')
```

Obviously not a blocker for me on anything, but thought I'd let you know.  Thanks!

**Comment by joke2k** [comment]
Thank you for reporting.
I do not know how to fix this without disabling the dollar, do you have any ideas?

**Comment by chromakey** [comment]
Not sure.  I just started using this library, so I'll dive into the code this weekend and see if I can come up with a PR.

**Comment by joke2k** [comment]
Wonderful, thank you again.

..and merry christmas

**Comment by edmorley** [comment]
Another option would be to deprecate the current proxied value syntax `$FOO` and switch to something like `${FOO}` which is much less likely to result in false positives when using random password generators.

**Comment by IlyaSemenov** [comment]
The recursive variable expansion that is currently in use needs to be documented at the very least! I was just hit by the same problem. The worst thing that it is **silenced** if the default is provided.

Consider the following example:

``` console
$ SECRET='$&^!@#' python -c "import environ; print(environ.Env()('SECRET', default=None))"
None
```

1) This is very counter-intuitive behaviour.
2) I don't think there is a way to actually provide that value via the environment variable.

**Comment by webyneter** [comment]
Hit the same issue with `$4$,p#^x/?isO[_MDUDQbuiL~nRnHA#tw(=:n8VVv>hZv-rq>8`.

**Comment by mrogaski** [comment]
I just hit this bug, also while expanding SECRET_KEY.

I don't think expansion should be applied to the value of environment variables at all.  Frankly, it's a significant security exposure.  

Expansion using `$FOO` or `${FOO}` in UN*X shells and `%FOO%` in Windows is done when setting the variables, but the variables are stored in their expanded form and are treated purely as opaque data by the shell when read and passed to the application. Expanding the values opens an application to a variety of parameter-tampering attacks, and I would argue that there's really no legitimate use for such behavior in a 12-factor design.

**Comment by sergeyklay** [comment]
I'm closing this issues in favor of https://github.com/joke2k/django-environ/issues/271
