### ISSUE TITLE
EMAIL_URL example

### ISSUE THREAD

**Issue by moimael** [joke2k/django-environ#7]
Hi,

It would be great to have an EMAIL_URL sample to see what syntax it accept, like for DATABASE_URL.

For example does it support username with an @ in it ?
Where do I put the smtp server + port ?

Thanks for this awesome project !

**Comment by joke2k** [comment]
We have to add this to documentation

**Comment by joke2k** [comment]
See #48 for the @ character.

**Comment by tonnyhideyori** [comment]
when i put my username, password ,host and port the docker-compose build breaks.
bringing this error :
ValueError: invalid literal for int() with base 10: 'B******3'
ERROR: Service 'nginx' failed to build: The command '/bin/sh -c env DD_SECRET_KEY='.' python3 manage.py collectstatic --noinput && true' returned a non-zero code: 1
I edited in settings.dist.py
EMAIL_CONFIG = env.email_url(
'DD_EMAIL_URL', default='smtp://A********C@:B*********3/x****************+9**G@email-smtp.eu-central-1.amazonaws.com:25')
when i remove slas("/")h in the password it does not break , hence what could be the problem

**Comment by sergeyklay** [comment]
@tonnyhideyori Please take a look at my answer for your issue in my fork https://github.com/sergeyklay/django-environ-2/issues/21#issuecomment-907619822
