### ISSUE TITLE
Cannot parse a list of tuples

### ISSUE THREAD

**Issue by lenarother** [joke2k/django-environ#75]
Hi @joke2k ,

thanks for an awesome project!

I was looking for a way to get a list of tuples parsed e.g. 
[('Bar', 'Bar'), ('Foo', 'Foo')]

This is as close as I can get:

```
MY_VAR='Bar,Bar;Foo,Foo'
MY_VAR = env.list('MY_VAR', default=[], cast=tuple)


('B', 'a', 'r'),
('B', 'a', 'r', ';', 'F', 'o', 'o'),
('F', 'o', 'o')]
```

Any tips how to deal with this?

Thanks,
Lena

**Comment by jorrit-wehelp** [comment]
Also see #47
It mentions that you could use the json type, but there's no tuple-like type in JSON. So you would get a list of lists.
But if the format of your environment variable is fixed and out of your control, you could write a custom function to parse this and pass it to the cast= parameter.

**Comment by esseti** [comment]
Same problem here, no news?

**Comment by sergeyklay** [comment]
The comment https://github.com/joke2k/django-environ/issues/47#issuecomment-167254176  explains how to get tuple of tuples. And the comment https://github.com/joke2k/django-environ/issues/47#issuecomment-461832572 demonstrates how to get list of tuples, such as ADMINS or MANAGERS. Finally, the comments explains how to use custom cat function. https://github.com/joke2k/django-environ/issues/75#issuecomment-182341994 Closing this.
