### ISSUE TITLE
does not load env variables from the .env file

### ISSUE THREAD

**Issue by musicformellons** [joke2k/django-environ#76]
I have an  .env file (in same folder as manage.py) with:
DJANGO_DEBUG=False
DATABASE_URL=postgres://user:pw@127.0.0.1:5432/dbname
POSTGRES_PASSWORD=pw
POSTGRES_USER=user
DJANGO_ADMIN_URL=r'^admin/'
DJANGO_SETTINGS_MODULE=config.settings.production
DJANGO_SECRET_KEY=7878078078078907890789087etc
DJANGO_ALLOWED_HOSTS=email.com
DJANGO_SERVER_EMAIL=info@email.com
DJANGO_SECURE_SSL_REDIRECT=False

But when I do:
python manage.py migrate --settings config.settings.production

I get:
django.core.exceptions.ImproperlyConfigured: Set the DJANGO_SECRET_KEY environment variable

Also env does not show any of the variables. The variables should have been loaded from my .env file right? So what's wrong?

BTW: I think the docs could be clearer on where to put the .env file and that is is loaded and when, I suppose. I looked elsewhere to find that that was indeed to be expected.

**Comment by musicformellons** [comment]
Solved it. The .env needs to be in the same folder as the settings files, not the manage.py file. Confusing as in the the Django Cookiecutter the env.example file is in the manage.py folder...

**Comment by tamj0rd2** [comment]
@musicformellons Would you mind sharing what your settings.py looks like? I'm having this issue and can't work it out

**Comment by metakermit** [comment]
I was having some problems with this too, but after specifying in *settings.py* the absolute path to where I keep my `.env` file (next to *manage.py*), running all the `manage.py` commands works.

    base = environ.Path(__file__) - 2 # two folders back (/a/b/ - 2 = /)
    environ.Env.read_env(env_file=base('.env')) # reading .env file

**Comment by alexforever86** [comment]
Modified this bit more so that if `ENV_PATH` is present, environment variables will be loaded from this file. 
```
env_file = '.env'
if not env.str('ENV_PATH', '.env') == '.env':
    env_file = env.str('ENV_PATH', '.env') + env_file

env.read_env(env_file=base(env_file))
```

**Comment by diek** [comment]
Easily the most complex setting of environmental variables I have ever dealt with, simply unbelievable.

**Comment by variable** [comment]
I have a PR to add ability to point to a env file via environment variable.

**Comment by efojs** [comment]
Guys 🤦‍♂️   
Spaces around ` = ` (equal sign) in `.env` file caused the same problem and nothing helped:
`SECRET_KEY = <secret_key>`  

Removing them solved the problem:  
`SECRET_KEY=<secret_key>`

**Comment by shaheem-pp** [comment]
> Solved it. The .env needs to be in the same folder as the settings files, not the manage.py file. Confusing as in the the Django Cookiecutter the env.example file is in the manage.py folder...

But I still have the issue
