### ISSUE TITLE
Can't set CONN_MAX_AGE to None

### ISSUE THREAD

**Issue by rubendura** [joke2k/django-environ#81]
When setting DATABASE_URL to something like `postgres://posgres@db:5432/postgres?conn_max_age=None` the end result is:

``` python
{
    'ENGINE': 'django.db.backends.postgresql_psycopg2',
    'HOST': 'db'
    'PORT': 5432,
    'USER': 'postgres',
    'PASSWORD': None,
    'NAME': 'postgres',
    'CONN_MAX_AGE': 'None',
    'OPTIONS': {},
}
```

Where CONN_MAX_AGE has an invalid value: it has to be set to either a float or None, but django-environ returns a str.

**Comment by murdav** [comment]
Did you solve this? Same problem for me.

**Comment by rubendura** [comment]
Nope, but as I want to have that anyway I ended up forcing that setting.

```python
DATABASES = {
    "default": env.db()
}
DATABASES['default']['CONN_MAX_AGE'] = None
```

**Comment by murdav** [comment]
@rubendura thanks for replying and confirmation. This is what I did too.

**Comment by joke2k** [comment]
@rubendura @murdav now options like CONN_MAX_AGE are better parsed.
Retry after few years :smiley:
