### ISSUE TITLE
Add documentation for proxied values

### ISSUE THREAD

**Issue by edmorley** [joke2k/django-environ#89]
With django-environ it's possible to have one environment variable refer to another, using this syntax:

```
CLOUDAMQP_URL=amqp://.....
BROKER_URL='$CLOUDAMQP_URL'
```

(Heroku escapes the environment variables, and so they are not expanded in `os.environ`, so this support from django-environ is very handy)

It would be good to document this feature in the readme :-)

**Comment by sergeyklay** [comment]
As far as I understand this functionality is already covered by the documentation. I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
