### ISSUE TITLE
Add external server

### ISSUE THREAD

**Issue by moimael** [joke2k/django-environ#9]
Hi again,

In our Django project we make ssh connections and scp to external server. 

Now they are configured like this:

SERVERS = {
    'asterisk': {
        'HOST': 'my_host',
        'PORT': '22',
        'LOGIN': 'login',
        'PASSWORD': 'password',
        'PKEY': '~/.ssh/id_rsa',
        'PKEY_SECRET': ''
    },
    'archive': {
        'HOST': 'host',
        'PORT': '22',
        'LOGIN': 'login',
        'PASSWORD': 'password',
        'PKEY': '~/.ssh/id_rsa',
        'PKEY_SECRET': ''
    }
}

What do you think about having something along env.db() (let's say env.server()) to manage this type of use case ?

Thanks !

**Comment by joke2k** [comment]
You can handle this with `env.url('ssh://host:port?pkey=...')` and then use the resulted dict to populate your package configuration.
