### ISSUE TITLE
RFC -- import all DJANGO__* variables from environment

### ISSUE THREAD

**Issue by jcushman** [joke2k/django-environ#90]
Hi! I have a new package I'm thinking of releasing, but that could also make sense to just fold into django-environ if you want it. I'd love to get your thoughts.

The basic idea is, instead of explicitly having to add `DEBUG = env('DEBUG')` to your `settings.py` file, you keep it as `DEBUG = False`. Then set `DJANGO__bool__DEBUG=True` in the environment and the setting gets picked up automatically.

This also works for sub-settings and for any data type supported by `django-environ`, so any of these are valid:

```
DJANGO__SECRET_KEY=secret
POSTGRES=postgres://uf07k1:wegauwhg@ec2-107-21-253-135.compute-1.amazonaws.com:5431/d8r82722
DJANGO__db__DATABASES__default=$POSTGRES
DJANGO__TEMPLATES__0__OPTIONS__context_processors__1='my.context.processor'
```

This works by adding a couple of lines at the bottom of your `settings.py` file or module:

```
import django_env_overrides
django_env_overrides.apply_to(globals())
```

Advantages are:
- You don't have to anticipate every setting you might want to override. If you suddenly want to try setting `DEBUG_PROPAGATE_EXCEPTIONS=True` on production, you just do `heroku config:set DJANGO__bool__DEBUG_PROPAGATE_EXCEPTIONS=True` and it's done.
- It's easy to have an app that runs in both 12-factor and non-12-factor environments. To deploy a non-12-factor app to Heroku, just add a buildpack that runs `echo "import django_env_overrides; django_env_overrides.apply_to(globals())" >> settings.py`

I have this ready to release here:

https://github.com/jcushman/django-env-overrides

But honestly I'd be just as happy to fold it into django-environ. Any thoughts about:
- whether it makes sense to fold into this package, and
- whether there's anything I should consider before releasing it as a separate package?

Thanks!

**Comment by beruic** [comment]
I'm not completely convinced this should be included in Django-environ. The strength of Django-environ is that it is very visible what you configure from environment variables, and what default values are.

### My comments to the feature in general
Overriding existing values like this, makes it easy to overlook what is going on. It would be easy for a new developer to get confused by why settings get overridden.

However, you could make it possible to perform these actions in the top of `settings.py`, which would mean that any settings in `settings.py` would override the environment. Thus you let the environment configure by omission of explicit definition in `settings.py`. Then you would only need a good comment to tell what is going on. Inspiration [here](http://stackoverflow.com/a/2933481/1031534).

You should also consider making it possible to state dependencies, which should raise ImproperlyConfigured, or make a warning (configurable behaviour) if something is not defined in the environment. This would probably make the above mentioned comment obsolete, as it would be clear what SHOULD be configured by environment.
Add default values here, and perhaps custom typing for non-standard variables, and BOOM, you have a VERY flexible and consise environment manager, which I personally would consider switching to.

Django-environ could be used to load a `.env` file, or you could build it into your own project.

**Comment by jcushman** [comment]
Thanks for your comments, beruic!

A first release of the package is now on PyPI: https://pypi.python.org/pypi/django-env-overrides

An offline conversation convinced me that you're right, this doesn't make sense in django-environ -- it's easy to misuse, and better to encourage people to be explicit where possible. But it's still a very handy add-on for interactive debugging of deployed code. Think of it like pdb for Django settings on Heroku -- it makes it easy to mess around with live settings and then record them explicitly once you get them figured out.

In general I would use this alongside django-environ. Use django-environ for stating dependencies, reading .env, etc., and django-env-overrides to allow overrides at the end. This also does allow settings.py to override the environment -- just put those settings after the override.

Putting it all together, you get something like this:

```
### explicit configuration via django-environ ###

import environ
env = environ.Env(DEBUG=(bool, False),)
env.read_env()  # read .env file if it exists

DEBUG = env('DEBUG')
DATABASES['default'] = env.db()
# etc.

### arbitrary overrides for interactive debugging ###

import django_env_overrides
django_env_overrides.apply_to(globals())

### anything that should change based on environment goes here ###

if DEBUG:
    MIDDLEWARE_CLASSES += ('cool.debugging.option')
```

**Comment by sergeyklay** [comment]
This curious idea actually has nothing to do with the current project (except it can use django-environ under the hood). Also as far as I can see the described project has successfully released. I want to close this issue because I don't want a bunch of these lying around. Thank you for the feedback and keeping us informed about your project :)
