### ISSUE TITLE
Inline comments does not work

### ISSUE THREAD

**Issue by beruic** [joke2k/django-environ#91]
If you put 

```
VARIABLE=SomeValue # Comment
```

in your `.env` file, the `# Comment` part is included in the value for `VARIABLE`, so its value becomes `SomeValue # Comment`.

**Comment by nunoh** [comment]
Just run into the same problem. +1

**Comment by SDF39679** [comment]
Also found this problem +1

**Comment by lvanderree** [comment]
I tried to fix this in https://github.com/joke2k/django-environ/pull/475

**Comment by sergeyklay** [comment]
This was introduced in #475 thanks to @lvanderree. We'll include this in the next release. Thank you for the report, and for helping us make django-environ better.
