### ISSUE TITLE
use redis in django-environ problem

### ISSUE THREAD

**Issue by steinliber** [joke2k/django-environ#95]
When use django-environ for redis，i meet a problem.the code for redis is 

```
'rediscache://127.0.0.1:6379/0?client_class=django_redis.client.DefaultClient'
```

and the problem is 

```
    response = receiver(signal=self, sender=sender, **named)
  File "./application/models.py", line 407, in clear_app_cache
    cache.delete(key)
  File "/srv/www/media.v3.client-api.dingdone.com/env/local/lib/python2.7/site-packages/django_redis/cache.py", line 38, in _decorator
    raise e.parent
ConnectionError: Error 2 connecting to unix socket: /0. No such file or directory.
```

The doc doesn't say about redis db set, Can anyone help

**Comment by jgoclawski** [comment]
`django-environ` 0.4 won't work with `django-redis` 4.5.0 (niwinz/django-redis#220). It also affects `django-cache-url` (ghickman/django-cache-url#29)
I think the issue might be fixed on master with #61. 
It would be great to have a new release on PyPi with this fix.
