### ISSUE TITLE
DATABASE_URL parser not work properly

### ISSUE THREAD

**Issue by eli-pavlov** [joke2k/django-environ#97]
If inside DATABASE_URL user password start with "# " character, then parser will build incorrect dict:

```
DATABASE_URL=mysql://user:#password@127.0.0.1:3306/dbname
```

res:

```
 {'ENGINE': 'django.db.backends.mysql', 'NAME': '', 'HOST': 'user', 'USER': None, 'PASSWORD': None, 'PORT': None}
```

python 2.7.6

**Comment by romerotron** [comment]
looks like it happens if a '#' is anywhere in the password FWIW

**Comment by joke2k** [comment]
Hi, there was some trouble with unquoted characters into parsed url string.
I do a commit and i'll release a new version (finally) to fix that.
Make sure to encode your url parts with `urllib.parse.encode` before set your string into `.env` file:
```
DATABASE_URL=mysql://user:%23password@127.0.0.1:3306/dbname
```

See #69 for more informations.
