### ISSUE TITLE
Variable values that starts with "$" are always treated as a reference

### ISSUE THREAD

**Issue by avrahamshukron** [joke2k/django-environ#98]
If you have something like:
`SECRET_KEY=$R3OHmJvC2Gi(5JaOMDTtO9-7#`
in your local.env file (I actually used this randomly generated key), then when loading the environment you'll get an error:
`django.core.exceptions.ImproperlyConfigured: Set the R3OHmJvC2Gi(5JaOMDTtO9-7# environment variable`

Notice how the "$" is missing from the exception message.
This is probably due to the "resolve proxied values"  you perform on lines 257-260 in `environ.py`

Not sure what the correct behavior should be, but this is definitely something that should be well-documented and advertised.

**Comment by joke2k** [comment]
hi @avrahamshukron 

to handle a value that starts with $ you have to use quotes like that:
`SECRET_KEY="$skipped-dollar-proxy-function"`

**Comment by avrahamshukron** [comment]
That's awesome, thanks!
