### ISSUE TITLE
docs: where did `vars()` come from?

### ISSUE THREAD

**Issue by glarrain** [joke2k/django-environ#99]
In the README, email settings:

```python
    EMAIL_CONFIG = env.email_url(
        'EMAIL_URL', default='smtp://user@:password@localhost:25')

    vars().update(EMAIL_CONFIG)
```

Where did that `vars()` come from? I have not found any reference to it, either in the README, the docs, or [in the repo](https://github.com/joke2k/django-environ/search?q=vars).

**Comment by joke2k** [comment]
You can find some references here:
https://docs.python.org/3/library/functions.html#vars

**Comment by glarrain** [comment]
Whoops, sorry.
(After 6 years of programming in Python I got bit by built-in function. Perhaps it has to do with my dislike of implicit assignments and global variables...)
